// Code generated by ent, DO NOT EDIT.

package tenantgroup

import (
	"ncobase/tenant/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldContainsFold(FieldID, id))
}

// TenantID applies equality check predicate on the "tenant_id" field. It's identical to TenantIDEQ.
func TenantID(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldEQ(FieldTenantID, v))
}

// GroupID applies equality check predicate on the "group_id" field. It's identical to GroupIDEQ.
func GroupID(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldEQ(FieldGroupID, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldEQ(FieldCreatedBy, v))
}

// UpdatedBy applies equality check predicate on the "updated_by" field. It's identical to UpdatedByEQ.
func UpdatedBy(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldEQ(FieldUpdatedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v int64) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// RelationType applies equality check predicate on the "relation_type" field. It's identical to RelationTypeEQ.
func RelationType(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldEQ(FieldRelationType, v))
}

// TenantIDEQ applies the EQ predicate on the "tenant_id" field.
func TenantIDEQ(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldEQ(FieldTenantID, v))
}

// TenantIDNEQ applies the NEQ predicate on the "tenant_id" field.
func TenantIDNEQ(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldNEQ(FieldTenantID, v))
}

// TenantIDIn applies the In predicate on the "tenant_id" field.
func TenantIDIn(vs ...string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldIn(FieldTenantID, vs...))
}

// TenantIDNotIn applies the NotIn predicate on the "tenant_id" field.
func TenantIDNotIn(vs ...string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldNotIn(FieldTenantID, vs...))
}

// TenantIDGT applies the GT predicate on the "tenant_id" field.
func TenantIDGT(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldGT(FieldTenantID, v))
}

// TenantIDGTE applies the GTE predicate on the "tenant_id" field.
func TenantIDGTE(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldGTE(FieldTenantID, v))
}

// TenantIDLT applies the LT predicate on the "tenant_id" field.
func TenantIDLT(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldLT(FieldTenantID, v))
}

// TenantIDLTE applies the LTE predicate on the "tenant_id" field.
func TenantIDLTE(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldLTE(FieldTenantID, v))
}

// TenantIDContains applies the Contains predicate on the "tenant_id" field.
func TenantIDContains(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldContains(FieldTenantID, v))
}

// TenantIDHasPrefix applies the HasPrefix predicate on the "tenant_id" field.
func TenantIDHasPrefix(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldHasPrefix(FieldTenantID, v))
}

// TenantIDHasSuffix applies the HasSuffix predicate on the "tenant_id" field.
func TenantIDHasSuffix(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldHasSuffix(FieldTenantID, v))
}

// TenantIDIsNil applies the IsNil predicate on the "tenant_id" field.
func TenantIDIsNil() predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldIsNull(FieldTenantID))
}

// TenantIDNotNil applies the NotNil predicate on the "tenant_id" field.
func TenantIDNotNil() predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldNotNull(FieldTenantID))
}

// TenantIDEqualFold applies the EqualFold predicate on the "tenant_id" field.
func TenantIDEqualFold(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldEqualFold(FieldTenantID, v))
}

// TenantIDContainsFold applies the ContainsFold predicate on the "tenant_id" field.
func TenantIDContainsFold(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldContainsFold(FieldTenantID, v))
}

// GroupIDEQ applies the EQ predicate on the "group_id" field.
func GroupIDEQ(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldEQ(FieldGroupID, v))
}

// GroupIDNEQ applies the NEQ predicate on the "group_id" field.
func GroupIDNEQ(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldNEQ(FieldGroupID, v))
}

// GroupIDIn applies the In predicate on the "group_id" field.
func GroupIDIn(vs ...string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldIn(FieldGroupID, vs...))
}

// GroupIDNotIn applies the NotIn predicate on the "group_id" field.
func GroupIDNotIn(vs ...string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldNotIn(FieldGroupID, vs...))
}

// GroupIDGT applies the GT predicate on the "group_id" field.
func GroupIDGT(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldGT(FieldGroupID, v))
}

// GroupIDGTE applies the GTE predicate on the "group_id" field.
func GroupIDGTE(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldGTE(FieldGroupID, v))
}

// GroupIDLT applies the LT predicate on the "group_id" field.
func GroupIDLT(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldLT(FieldGroupID, v))
}

// GroupIDLTE applies the LTE predicate on the "group_id" field.
func GroupIDLTE(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldLTE(FieldGroupID, v))
}

// GroupIDContains applies the Contains predicate on the "group_id" field.
func GroupIDContains(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldContains(FieldGroupID, v))
}

// GroupIDHasPrefix applies the HasPrefix predicate on the "group_id" field.
func GroupIDHasPrefix(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldHasPrefix(FieldGroupID, v))
}

// GroupIDHasSuffix applies the HasSuffix predicate on the "group_id" field.
func GroupIDHasSuffix(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldHasSuffix(FieldGroupID, v))
}

// GroupIDIsNil applies the IsNil predicate on the "group_id" field.
func GroupIDIsNil() predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldIsNull(FieldGroupID))
}

// GroupIDNotNil applies the NotNil predicate on the "group_id" field.
func GroupIDNotNil() predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldNotNull(FieldGroupID))
}

// GroupIDEqualFold applies the EqualFold predicate on the "group_id" field.
func GroupIDEqualFold(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldEqualFold(FieldGroupID, v))
}

// GroupIDContainsFold applies the ContainsFold predicate on the "group_id" field.
func GroupIDContainsFold(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldContainsFold(FieldGroupID, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByContains applies the Contains predicate on the "created_by" field.
func CreatedByContains(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldContains(FieldCreatedBy, v))
}

// CreatedByHasPrefix applies the HasPrefix predicate on the "created_by" field.
func CreatedByHasPrefix(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldHasPrefix(FieldCreatedBy, v))
}

// CreatedByHasSuffix applies the HasSuffix predicate on the "created_by" field.
func CreatedByHasSuffix(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldHasSuffix(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldNotNull(FieldCreatedBy))
}

// CreatedByEqualFold applies the EqualFold predicate on the "created_by" field.
func CreatedByEqualFold(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldEqualFold(FieldCreatedBy, v))
}

// CreatedByContainsFold applies the ContainsFold predicate on the "created_by" field.
func CreatedByContainsFold(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldContainsFold(FieldCreatedBy, v))
}

// UpdatedByEQ applies the EQ predicate on the "updated_by" field.
func UpdatedByEQ(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldEQ(FieldUpdatedBy, v))
}

// UpdatedByNEQ applies the NEQ predicate on the "updated_by" field.
func UpdatedByNEQ(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldNEQ(FieldUpdatedBy, v))
}

// UpdatedByIn applies the In predicate on the "updated_by" field.
func UpdatedByIn(vs ...string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldIn(FieldUpdatedBy, vs...))
}

// UpdatedByNotIn applies the NotIn predicate on the "updated_by" field.
func UpdatedByNotIn(vs ...string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldNotIn(FieldUpdatedBy, vs...))
}

// UpdatedByGT applies the GT predicate on the "updated_by" field.
func UpdatedByGT(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldGT(FieldUpdatedBy, v))
}

// UpdatedByGTE applies the GTE predicate on the "updated_by" field.
func UpdatedByGTE(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldGTE(FieldUpdatedBy, v))
}

// UpdatedByLT applies the LT predicate on the "updated_by" field.
func UpdatedByLT(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldLT(FieldUpdatedBy, v))
}

// UpdatedByLTE applies the LTE predicate on the "updated_by" field.
func UpdatedByLTE(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldLTE(FieldUpdatedBy, v))
}

// UpdatedByContains applies the Contains predicate on the "updated_by" field.
func UpdatedByContains(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldContains(FieldUpdatedBy, v))
}

// UpdatedByHasPrefix applies the HasPrefix predicate on the "updated_by" field.
func UpdatedByHasPrefix(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldHasPrefix(FieldUpdatedBy, v))
}

// UpdatedByHasSuffix applies the HasSuffix predicate on the "updated_by" field.
func UpdatedByHasSuffix(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldHasSuffix(FieldUpdatedBy, v))
}

// UpdatedByIsNil applies the IsNil predicate on the "updated_by" field.
func UpdatedByIsNil() predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldIsNull(FieldUpdatedBy))
}

// UpdatedByNotNil applies the NotNil predicate on the "updated_by" field.
func UpdatedByNotNil() predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldNotNull(FieldUpdatedBy))
}

// UpdatedByEqualFold applies the EqualFold predicate on the "updated_by" field.
func UpdatedByEqualFold(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldEqualFold(FieldUpdatedBy, v))
}

// UpdatedByContainsFold applies the ContainsFold predicate on the "updated_by" field.
func UpdatedByContainsFold(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldContainsFold(FieldUpdatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldLTE(FieldCreatedAt, v))
}

// CreatedAtIsNil applies the IsNil predicate on the "created_at" field.
func CreatedAtIsNil() predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldIsNull(FieldCreatedAt))
}

// CreatedAtNotNil applies the NotNil predicate on the "created_at" field.
func CreatedAtNotNil() predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldNotNull(FieldCreatedAt))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v int64) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v int64) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...int64) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...int64) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v int64) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v int64) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v int64) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v int64) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldLTE(FieldUpdatedAt, v))
}

// UpdatedAtIsNil applies the IsNil predicate on the "updated_at" field.
func UpdatedAtIsNil() predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldIsNull(FieldUpdatedAt))
}

// UpdatedAtNotNil applies the NotNil predicate on the "updated_at" field.
func UpdatedAtNotNil() predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldNotNull(FieldUpdatedAt))
}

// RelationTypeEQ applies the EQ predicate on the "relation_type" field.
func RelationTypeEQ(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldEQ(FieldRelationType, v))
}

// RelationTypeNEQ applies the NEQ predicate on the "relation_type" field.
func RelationTypeNEQ(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldNEQ(FieldRelationType, v))
}

// RelationTypeIn applies the In predicate on the "relation_type" field.
func RelationTypeIn(vs ...string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldIn(FieldRelationType, vs...))
}

// RelationTypeNotIn applies the NotIn predicate on the "relation_type" field.
func RelationTypeNotIn(vs ...string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldNotIn(FieldRelationType, vs...))
}

// RelationTypeGT applies the GT predicate on the "relation_type" field.
func RelationTypeGT(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldGT(FieldRelationType, v))
}

// RelationTypeGTE applies the GTE predicate on the "relation_type" field.
func RelationTypeGTE(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldGTE(FieldRelationType, v))
}

// RelationTypeLT applies the LT predicate on the "relation_type" field.
func RelationTypeLT(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldLT(FieldRelationType, v))
}

// RelationTypeLTE applies the LTE predicate on the "relation_type" field.
func RelationTypeLTE(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldLTE(FieldRelationType, v))
}

// RelationTypeContains applies the Contains predicate on the "relation_type" field.
func RelationTypeContains(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldContains(FieldRelationType, v))
}

// RelationTypeHasPrefix applies the HasPrefix predicate on the "relation_type" field.
func RelationTypeHasPrefix(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldHasPrefix(FieldRelationType, v))
}

// RelationTypeHasSuffix applies the HasSuffix predicate on the "relation_type" field.
func RelationTypeHasSuffix(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldHasSuffix(FieldRelationType, v))
}

// RelationTypeEqualFold applies the EqualFold predicate on the "relation_type" field.
func RelationTypeEqualFold(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldEqualFold(FieldRelationType, v))
}

// RelationTypeContainsFold applies the ContainsFold predicate on the "relation_type" field.
func RelationTypeContainsFold(v string) predicate.TenantGroup {
	return predicate.TenantGroup(sql.FieldContainsFold(FieldRelationType, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TenantGroup) predicate.TenantGroup {
	return predicate.TenantGroup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TenantGroup) predicate.TenantGroup {
	return predicate.TenantGroup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TenantGroup) predicate.TenantGroup {
	return predicate.TenantGroup(sql.NotPredicates(p))
}
