WITH tenant AS
         (SELECT id FROM ncse_tenant LIMIT 1),
     user_ids AS
         (SELECT id, username FROM ncse_user)
INSERT
INTO ncse_menu (id, name, label, slug, type, path, target, icon, perms, hidden, "order", disabled, extras, parent_id,
                tenant_id, created_by, updated_by, created_at, updated_at)
VALUES
  -- menus
  ('ys9kdxnj592ucg2_', '系统设置', 'system.basic.setting.navigation', 'submenu-system-setting', 'submenu',
   '/system/basic', null, null, null, null, 470, null, '{}', 'eq2af_zozawwkg2v', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('avm-snd11gja4s63', '菜单', 'system.menu.navigation', 'system-menus', 'sidebar', '/system/menu', null, 'IconMenu',
   null, null, 940, null, '{}', '7zjxqssfk_t7d4j5', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('rfp_r30vaeb1d3bf', '我的帐号', 'dropdowns.account.profile.label', 'account-profile', 'account', '/account/profile',
   null, 'IconUser', null, null, 99, null, '{}', null, (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('6plu5kjd0_fqtvgk', '模型', 'example.card.model.navigation', 'submenu-model-group', 'submenu', '-', null, null, null,
   null, 490, null, '{}', 'dvokvdati7gt3c74', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('hoqqfio8pf7p_oju', '列表 2', 'example.list2.navigation', 'example-list-2', 'sidebar', '/example/list-2', null,
   'IconTableAlias', null, null, 98, null, '{}', 'uzzp22kr8xeffc2f', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('99j-__jgfpr_jg5_', '任务', 'example.card.efficiency.task.navigation', 'submenu-efficiency-task', 'submenu',
   '/example/card/task', null, null, null, null, 260, null, '{}', 'dvokvdati7gt3c74', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('3eq8sxv5bq8fw1qk', '组件', 'example.card.component.navigation', 'submenu-component-group', 'submenu', '-', null,
   null, null, null, 390, null, '{}', 'dvokvdati7gt3c74', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('hw7ookij6r6_xhrz', '北京', 'content.news.cn.beijing.navigation', 'content-news-cn-beijing', 'main',
   '/content/news/cn-beijing', null, null, null, null, 99, null, '{}', 'p8w_xq79_3t5x6em', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('rj7d3fvdu2u12omn', '退出', 'dropdowns.account.logout.label', 'account-logout', 'account', '/logout', null,
   'IconLogout', null, null, 0, null, '{}', null, (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('5y8s30i29gmpa5y9', '分析', 'example.analyze.navigation', 'example-analyze', 'sidebar', '/example/analyze', null,
   'IconDeviceAnalytics', null, null, 98, null, '{}', 'uzzp22kr8xeffc2f', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('88u8qt61x_w3jcs6', '元素', 'example.card.component.element.navigation', 'submenu-component-element', 'submenu',
   '/example/card/element', null, null, null, null, 350, null, '{}', 'dvokvdati7gt3c74', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('aex3rovov5s_myy6', '流程', 'example.card.efficiency.workflow.navigation', 'submenu-efficiency-workflow', 'submenu',
   '/example/card/workflow', null, null, null, null, 250, null, '{}', 'dvokvdati7gt3c74', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('0gpbmhv29c7ixqff', '组件', 'content.component.navigation', 'content-component', 'sidebar', '/content/component',
   null, 'IconComponents', null, null, 93, null, '{}', '3xnwblr6ixuv5rk-', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('xxwkunp6rae62xgo', '瀑布流', 'example.masonry.navigation', 'example-masonry', 'sidebar', '/example/masonry', null,
   'IconLayoutBoard', null, null, 98, null, '{}', 'uzzp22kr8xeffc2f', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('_nx1vai8u-k4dyfa', 'divide', null, null, 'sidebar', '-', null, null, null, null, 92, null, '{}', '3xnwblr6ixuv5rk-',
   (SELECT id FROM tenant), (SELECT id FROM user_ids WHERE username = 'admin'),
   (SELECT id FROM user_ids WHERE username = 'admin'), EXTRACT(EPOCH FROM now()) * 1000,
   EXTRACT(EPOCH FROM now()) * 1000),
  ('m6y31db8yd7hh3ga', 'divide', null, null, 'sidebar', '-', null, null, null, null, 97, null, '{}', '3xnwblr6ixuv5rk-',
   (SELECT id FROM tenant), (SELECT id FROM user_ids WHERE username = 'admin'),
   (SELECT id FROM user_ids WHERE username = 'admin'), EXTRACT(EPOCH FROM now()) * 1000,
   EXTRACT(EPOCH FROM now()) * 1000),
  ('lzvitw7qk6dzcqow', '德国', 'content.news.de.navigation', 'content-news-de', 'main', '/content/news/de', null, null,
   null, null, 99, null, '{}', 'm6y31db8yd7hh3ga', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('9kjn8c7olfy_mve1', 'UI 库', 'example.ui.navigation', 'example-ui', 'sidebar', '/example/ui/elements', null,
   'IconBrandSupernova', null, null, 98, null, '{}', 'uzzp22kr8xeffc2f', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('pu73e_6bd8ga5os4', '租户', 'system.tenant.navigation', 'system-tenant', 'sidebar', '/system/tenant', null,
   'IconBuildingCommunity', null, null, 999, null, '{}', '7zjxqssfk_t7d4j5', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('d7hodbcrl99f_mm_', '天津', 'content.news.cn.tianjin.navigation', 'content-news-cn-tianjin', 'main',
   '/content/news/cn-tianjin', null, null, null, null, 99, null, '{}', 'p8w_xq79_3t5x6em', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('ks-94u_vhrxn3bem', '列表 1', 'example.list1.navigation', 'example-list-1', 'sidebar', '/example/list-1', null,
   'IconTable', null, null, 98, null, '{}', 'uzzp22kr8xeffc2f', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('4n4n-w245jy_k9i_', 'divide', null, null, 'sidebar', '-', null, null, null, null, 920, null, '{}',
   '7zjxqssfk_t7d4j5', (SELECT id FROM tenant), (SELECT id FROM user_ids WHERE username = 'admin'),
   (SELECT id FROM user_ids WHERE username = 'admin'), EXTRACT(EPOCH FROM now()) * 1000,
   EXTRACT(EPOCH FROM now()) * 1000),
  ('3eho8y5voih2omy7', '控制台', 'dashboard.navigation', 'dashboard', 'header', '/dash', null, 'IconGauge', null, null,
   99, null, '{}', null, (SELECT id FROM tenant), (SELECT id FROM user_ids WHERE username = 'admin'),
   (SELECT id FROM user_ids WHERE username = 'admin'), EXTRACT(EPOCH FROM now()) * 1000,
   EXTRACT(EPOCH FROM now()) * 1000),
  ('iklf1qnqo0c71s7t', '权限', 'system.permission.navigation', 'system-permission', 'sidebar', '/system/permission',
   null, 'IconLockAccess', null, null, 930, null, '{}', '7zjxqssfk_t7d4j5', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('n_gi_ch0ee4uzjs-', '美国', 'content.news.us.navigation', 'content-news-us', 'main', '/content/news/us', null, null,
   null, null, 99, null, '{}', 'm6y31db8yd7hh3ga', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('ap0poo0lc_izlu51', '效率', 'example.card.efficiency.navigation', 'submenu-efficiency-group', 'submenu', '-', null,
   null, null, null, 290, null, '{}', 'dvokvdati7gt3c74', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('7zjxqssfk_t7d4j5', '系统', 'system.navigation', 'system', 'header', '/system/tenant', null, null, null, null, 10,
   null, '{}', null, (SELECT id FROM tenant), (SELECT id FROM user_ids WHERE username = 'admin'),
   (SELECT id FROM user_ids WHERE username = 'admin'), EXTRACT(EPOCH FROM now()) * 1000,
   EXTRACT(EPOCH FROM now()) * 1000),
  ('2antdxi9qzz-oduw', '审批', 'content.approval.navigation', 'content-approval', 'sidebar', '/content/approval', null,
   'IconChecklist', null, null, 95, null, '{}', '3xnwblr6ixuv5rk-', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('3ldt_xt4gb8phlx6', '报表', 'example.card.efficiency.report.navigation', 'submenu-efficiency-report', 'submenu',
   '/example/card/report', null, null, null, null, 270, null, '{}', 'dvokvdati7gt3c74', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('06lfwenh83pjblp4', '河北', 'content.news.cn.hebei.navigation', 'content-news-cn-hebei', 'main',
   '/content/news/cn-hebei', null, null, null, null, 99, null, '{}', 'p8w_xq79_3t5x6em', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('dviwf5l2m7k1mdqi', '切换租户', 'dropdowns.tenant.switch.label', 'tenant-switch', 'tenant', null, null, 'IconSwitch',
   null, null, 99, null, '{}', null, (SELECT id FROM tenant), (SELECT id FROM user_ids WHERE username = 'admin'),
   (SELECT id FROM user_ids WHERE username = 'admin'), EXTRACT(EPOCH FROM now()) * 1000,
   EXTRACT(EPOCH FROM now()) * 1000),
  ('00mtjp0uip0ef6qj', '布局', 'example.card.component.layout.navigation', 'submenu-component-layout', 'submenu',
   '/example/card/layout', null, null, null, null, 370, null, '{}', 'dvokvdati7gt3c74', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('ep29h_ct05o06xwp', 'divide', null, null, 'sidebar', '-', null, null, null, null, 950, null, '{}',
   '7zjxqssfk_t7d4j5', (SELECT id FROM tenant), (SELECT id FROM user_ids WHERE username = 'admin'),
   (SELECT id FROM user_ids WHERE username = 'admin'), EXTRACT(EPOCH FROM now()) * 1000,
   EXTRACT(EPOCH FROM now()) * 1000),
  ('2eoct_k3m8ahyi62', '角色', 'system.role.navigation', 'system-role', 'sidebar', '/system/role', null,
   'IconUsersGroup', null, null, 970, null, '{}', '7zjxqssfk_t7d4j5', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('dvokvdati7gt3c74', '卡片', 'example.card.navigation', 'example-card', 'sidebar', '/example/card', null, 'IconCards',
   null, null, 98, null, '{}', 'uzzp22kr8xeffc2f', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('szd0w8w-cpao3ciz', '回收站', 'content.trash.navigation', 'content-trash', 'sidebar', '/content/trash', null,
   'IconTrash', null, null, 91, null, '{}', '3xnwblr6ixuv5rk-', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('cxv-hxh7sruve4n_', '用户', 'example.card.model.user.navigation', 'submenu-model-user', 'submenu',
   '/example/card/user', null, null, null, null, 460, null, '{}', 'dvokvdati7gt3c74', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('8w2zakmv6yug026r', '组织', 'system.group.navigation', 'system-group', 'sidebar', '/system/group', null,
   'IconBinaryTree2', null, null, 990, null, '{}', '7zjxqssfk_t7d4j5', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('emaflle-9yz9svd6', '角色', 'example.card.model.role.navigation', 'submenu-model-role', 'submenu',
   '/example/card/role', null, null, null, null, 470, null, '{}', 'dvokvdati7gt3c74', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('xckkq4p8d8vc5tqf', '租户', null, 'tenant-dropdown-menu-label', 'tenant', '-', null, null, null, null, 100, null,
   '{}', null, (SELECT id FROM tenant), (SELECT id FROM user_ids WHERE username = 'admin'),
   (SELECT id FROM user_ids WHERE username = 'admin'), EXTRACT(EPOCH FROM now()) * 1000,
   EXTRACT(EPOCH FROM now()) * 1000),
  ('uzzp22kr8xeffc2f', '示例', 'example.navigation', 'example', 'header', '/example/card', null, null, null, null, 0,
   null, '{}', null, (SELECT id FROM tenant), (SELECT id FROM user_ids WHERE username = 'admin'),
   (SELECT id FROM user_ids WHERE username = 'admin'), EXTRACT(EPOCH FROM now()) * 1000,
   EXTRACT(EPOCH FROM now()) * 1000),
  ('3xnwblr6ixuv5rk-', '内容', 'content.navigation', 'content', 'header', '/content/topic', null, null, null, null, 98,
   null, '{}', null, (SELECT id FROM tenant), (SELECT id FROM user_ids WHERE username = 'admin'),
   (SELECT id FROM user_ids WHERE username = 'admin'), EXTRACT(EPOCH FROM now()) * 1000,
   EXTRACT(EPOCH FROM now()) * 1000),
  ('p8w_xq79_3t5x6em', '中国', 'content.news.cn.navigation', 'content-news-cn', 'main', '/content/news/cn', null, null,
   null, null, 99, null, '{}', 'm6y31db8yd7hh3ga', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('itoso8qgr3q53sxe', '权限', 'example.card.model.permission.navigation', 'submenu-model-permission', 'submenu',
   '/example/card/permission', null, null, null, null, 480, null, '{}', 'dvokvdati7gt3c74', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('rhd1pik01pe2tkit', '字典', 'system.dictionary.navigation', 'system-dictionary', 'sidebar', '/system/dictionary',
   null, 'IconVocabulary', null, null, 910, null, '{}', '7zjxqssfk_t7d4j5', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('9yb7vrsfciiy-s-y', '模板', 'example.card.component.template.navigation', 'submenu-component-template', 'submenu',
   '/example/card/template', null, null, null, null, 380, null, '{}', 'dvokvdati7gt3c74', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('vg-wuh9w81kuywyo', '栏目', 'content.taxonomy.navigation', 'content-taxonomy', 'sidebar', '/content/taxonomy', null,
   'IconColumns', null, null, 98, null, '{}', '3xnwblr6ixuv5rk-', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('7sh5f7d1a67kp6gw', '评论', 'content.comment.navigation', 'content-comment', 'sidebar', '/content/comment', null,
   'IconMessage', null, null, 96, null, '{}', '3xnwblr6ixuv5rk-', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('_7xck111bmh8l5yc', '用户', 'system.user.navigation', 'system-user', 'sidebar', '/system/user', null, 'IconUsers',
   null, null, 980, null, '{}', '7zjxqssfk_t7d4j5', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('cc0gp5r7yj-iypbo', '主题', 'content.topic.navigation', 'content-topic', 'sidebar', '/content/topic', null,
   'IconArticle', null, null, 99, null, '{}', '3xnwblr6ixuv5rk-', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('5v8umiuinx26ollv', '表单', 'example.card.component.form.navigation', 'submenu-component-form', 'submenu',
   '/example/card/form', null, null, null, null, 360, null, '{}', 'dvokvdati7gt3c74', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('y1m86dwexkommwp3', '日志', 'example.card.efficiency.log.navigation', 'submenu-efficiency-log', 'submenu',
   '/example/card/log', null, null, null, null, 280, null, '{}', 'dvokvdati7gt3c74', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('eq2af_zozawwkg2v', '基础设置', 'system.basic.navigation', 'system-basic', 'sidebar', '/system/basic', '_self',
   'IconSettings2', null, null, 99, null, '{}', '7zjxqssfk_t7d4j5', (SELECT id FROM tenant),
   (SELECT id FROM user_ids WHERE username = 'admin'), (SELECT id FROM user_ids WHERE username = 'admin'),
   EXTRACT(EPOCH FROM now()) * 1000, EXTRACT(EPOCH FROM now()) * 1000),
  ('qys3d54c5w7n2sm9', 'divide', null, null, 'sidebar', '-', null, null, null, null, 94, null, '{}', '3xnwblr6ixuv5rk-',
   (SELECT id FROM tenant), (SELECT id FROM user_ids WHERE username = 'admin'),
   (SELECT id FROM user_ids WHERE username = 'admin'), EXTRACT(EPOCH FROM now()) * 1000,
   EXTRACT(EPOCH FROM now()) * 1000);
