// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ncobase/core/realtime/data/ent/notification"
	"ncobase/core/realtime/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// NotificationUpdate is the builder for updating Notification entities.
type NotificationUpdate struct {
	config
	hooks    []Hook
	mutation *NotificationMutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (nu *NotificationUpdate) Where(ps ...predicate.Notification) *NotificationUpdate {
	nu.mutation.Where(ps...)
	return nu
}

// SetTitle sets the "title" field.
func (nu *NotificationUpdate) SetTitle(s string) *NotificationUpdate {
	nu.mutation.SetTitle(s)
	return nu
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableTitle(s *string) *NotificationUpdate {
	if s != nil {
		nu.SetTitle(*s)
	}
	return nu
}

// ClearTitle clears the value of the "title" field.
func (nu *NotificationUpdate) ClearTitle() *NotificationUpdate {
	nu.mutation.ClearTitle()
	return nu
}

// SetContent sets the "content" field.
func (nu *NotificationUpdate) SetContent(s string) *NotificationUpdate {
	nu.mutation.SetContent(s)
	return nu
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableContent(s *string) *NotificationUpdate {
	if s != nil {
		nu.SetContent(*s)
	}
	return nu
}

// ClearContent clears the value of the "content" field.
func (nu *NotificationUpdate) ClearContent() *NotificationUpdate {
	nu.mutation.ClearContent()
	return nu
}

// SetType sets the "type" field.
func (nu *NotificationUpdate) SetType(s string) *NotificationUpdate {
	nu.mutation.SetType(s)
	return nu
}

// SetNillableType sets the "type" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableType(s *string) *NotificationUpdate {
	if s != nil {
		nu.SetType(*s)
	}
	return nu
}

// ClearType clears the value of the "type" field.
func (nu *NotificationUpdate) ClearType() *NotificationUpdate {
	nu.mutation.ClearType()
	return nu
}

// SetUserID sets the "user_id" field.
func (nu *NotificationUpdate) SetUserID(s string) *NotificationUpdate {
	nu.mutation.SetUserID(s)
	return nu
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableUserID(s *string) *NotificationUpdate {
	if s != nil {
		nu.SetUserID(*s)
	}
	return nu
}

// ClearUserID clears the value of the "user_id" field.
func (nu *NotificationUpdate) ClearUserID() *NotificationUpdate {
	nu.mutation.ClearUserID()
	return nu
}

// SetStatus sets the "status" field.
func (nu *NotificationUpdate) SetStatus(i int) *NotificationUpdate {
	nu.mutation.ResetStatus()
	nu.mutation.SetStatus(i)
	return nu
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableStatus(i *int) *NotificationUpdate {
	if i != nil {
		nu.SetStatus(*i)
	}
	return nu
}

// AddStatus adds i to the "status" field.
func (nu *NotificationUpdate) AddStatus(i int) *NotificationUpdate {
	nu.mutation.AddStatus(i)
	return nu
}

// SetLinks sets the "links" field.
func (nu *NotificationUpdate) SetLinks(m []map[string]interface{}) *NotificationUpdate {
	nu.mutation.SetLinks(m)
	return nu
}

// AppendLinks appends m to the "links" field.
func (nu *NotificationUpdate) AppendLinks(m []map[string]interface{}) *NotificationUpdate {
	nu.mutation.AppendLinks(m)
	return nu
}

// ClearLinks clears the value of the "links" field.
func (nu *NotificationUpdate) ClearLinks() *NotificationUpdate {
	nu.mutation.ClearLinks()
	return nu
}

// SetChannelID sets the "channel_id" field.
func (nu *NotificationUpdate) SetChannelID(s string) *NotificationUpdate {
	nu.mutation.SetChannelID(s)
	return nu
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (nu *NotificationUpdate) SetNillableChannelID(s *string) *NotificationUpdate {
	if s != nil {
		nu.SetChannelID(*s)
	}
	return nu
}

// ClearChannelID clears the value of the "channel_id" field.
func (nu *NotificationUpdate) ClearChannelID() *NotificationUpdate {
	nu.mutation.ClearChannelID()
	return nu
}

// SetUpdatedAt sets the "updated_at" field.
func (nu *NotificationUpdate) SetUpdatedAt(i int64) *NotificationUpdate {
	nu.mutation.ResetUpdatedAt()
	nu.mutation.SetUpdatedAt(i)
	return nu
}

// AddUpdatedAt adds i to the "updated_at" field.
func (nu *NotificationUpdate) AddUpdatedAt(i int64) *NotificationUpdate {
	nu.mutation.AddUpdatedAt(i)
	return nu
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (nu *NotificationUpdate) ClearUpdatedAt() *NotificationUpdate {
	nu.mutation.ClearUpdatedAt()
	return nu
}

// Mutation returns the NotificationMutation object of the builder.
func (nu *NotificationUpdate) Mutation() *NotificationMutation {
	return nu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (nu *NotificationUpdate) Save(ctx context.Context) (int, error) {
	nu.defaults()
	return withHooks(ctx, nu.sqlSave, nu.mutation, nu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nu *NotificationUpdate) SaveX(ctx context.Context) int {
	affected, err := nu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (nu *NotificationUpdate) Exec(ctx context.Context) error {
	_, err := nu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nu *NotificationUpdate) ExecX(ctx context.Context) {
	if err := nu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nu *NotificationUpdate) defaults() {
	if _, ok := nu.mutation.UpdatedAt(); !ok && !nu.mutation.UpdatedAtCleared() {
		v := notification.UpdateDefaultUpdatedAt()
		nu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nu *NotificationUpdate) check() error {
	if v, ok := nu.mutation.UserID(); ok {
		if err := notification.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Notification.user_id": %w`, err)}
		}
	}
	if v, ok := nu.mutation.ChannelID(); ok {
		if err := notification.ChannelIDValidator(v); err != nil {
			return &ValidationError{Name: "channel_id", err: fmt.Errorf(`ent: validator failed for field "Notification.channel_id": %w`, err)}
		}
	}
	return nil
}

func (nu *NotificationUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := nu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeString))
	if ps := nu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nu.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if nu.mutation.TitleCleared() {
		_spec.ClearField(notification.FieldTitle, field.TypeString)
	}
	if value, ok := nu.mutation.Content(); ok {
		_spec.SetField(notification.FieldContent, field.TypeString, value)
	}
	if nu.mutation.ContentCleared() {
		_spec.ClearField(notification.FieldContent, field.TypeString)
	}
	if value, ok := nu.mutation.GetType(); ok {
		_spec.SetField(notification.FieldType, field.TypeString, value)
	}
	if nu.mutation.TypeCleared() {
		_spec.ClearField(notification.FieldType, field.TypeString)
	}
	if value, ok := nu.mutation.UserID(); ok {
		_spec.SetField(notification.FieldUserID, field.TypeString, value)
	}
	if nu.mutation.UserIDCleared() {
		_spec.ClearField(notification.FieldUserID, field.TypeString)
	}
	if value, ok := nu.mutation.Status(); ok {
		_spec.SetField(notification.FieldStatus, field.TypeInt, value)
	}
	if value, ok := nu.mutation.AddedStatus(); ok {
		_spec.AddField(notification.FieldStatus, field.TypeInt, value)
	}
	if value, ok := nu.mutation.Links(); ok {
		_spec.SetField(notification.FieldLinks, field.TypeJSON, value)
	}
	if value, ok := nu.mutation.AppendedLinks(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, notification.FieldLinks, value)
		})
	}
	if nu.mutation.LinksCleared() {
		_spec.ClearField(notification.FieldLinks, field.TypeJSON)
	}
	if value, ok := nu.mutation.ChannelID(); ok {
		_spec.SetField(notification.FieldChannelID, field.TypeString, value)
	}
	if nu.mutation.ChannelIDCleared() {
		_spec.ClearField(notification.FieldChannelID, field.TypeString)
	}
	if nu.mutation.CreatedAtCleared() {
		_spec.ClearField(notification.FieldCreatedAt, field.TypeInt64)
	}
	if value, ok := nu.mutation.UpdatedAt(); ok {
		_spec.SetField(notification.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := nu.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(notification.FieldUpdatedAt, field.TypeInt64, value)
	}
	if nu.mutation.UpdatedAtCleared() {
		_spec.ClearField(notification.FieldUpdatedAt, field.TypeInt64)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, nu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	nu.mutation.done = true
	return n, nil
}

// NotificationUpdateOne is the builder for updating a single Notification entity.
type NotificationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *NotificationMutation
}

// SetTitle sets the "title" field.
func (nuo *NotificationUpdateOne) SetTitle(s string) *NotificationUpdateOne {
	nuo.mutation.SetTitle(s)
	return nuo
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableTitle(s *string) *NotificationUpdateOne {
	if s != nil {
		nuo.SetTitle(*s)
	}
	return nuo
}

// ClearTitle clears the value of the "title" field.
func (nuo *NotificationUpdateOne) ClearTitle() *NotificationUpdateOne {
	nuo.mutation.ClearTitle()
	return nuo
}

// SetContent sets the "content" field.
func (nuo *NotificationUpdateOne) SetContent(s string) *NotificationUpdateOne {
	nuo.mutation.SetContent(s)
	return nuo
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableContent(s *string) *NotificationUpdateOne {
	if s != nil {
		nuo.SetContent(*s)
	}
	return nuo
}

// ClearContent clears the value of the "content" field.
func (nuo *NotificationUpdateOne) ClearContent() *NotificationUpdateOne {
	nuo.mutation.ClearContent()
	return nuo
}

// SetType sets the "type" field.
func (nuo *NotificationUpdateOne) SetType(s string) *NotificationUpdateOne {
	nuo.mutation.SetType(s)
	return nuo
}

// SetNillableType sets the "type" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableType(s *string) *NotificationUpdateOne {
	if s != nil {
		nuo.SetType(*s)
	}
	return nuo
}

// ClearType clears the value of the "type" field.
func (nuo *NotificationUpdateOne) ClearType() *NotificationUpdateOne {
	nuo.mutation.ClearType()
	return nuo
}

// SetUserID sets the "user_id" field.
func (nuo *NotificationUpdateOne) SetUserID(s string) *NotificationUpdateOne {
	nuo.mutation.SetUserID(s)
	return nuo
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableUserID(s *string) *NotificationUpdateOne {
	if s != nil {
		nuo.SetUserID(*s)
	}
	return nuo
}

// ClearUserID clears the value of the "user_id" field.
func (nuo *NotificationUpdateOne) ClearUserID() *NotificationUpdateOne {
	nuo.mutation.ClearUserID()
	return nuo
}

// SetStatus sets the "status" field.
func (nuo *NotificationUpdateOne) SetStatus(i int) *NotificationUpdateOne {
	nuo.mutation.ResetStatus()
	nuo.mutation.SetStatus(i)
	return nuo
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableStatus(i *int) *NotificationUpdateOne {
	if i != nil {
		nuo.SetStatus(*i)
	}
	return nuo
}

// AddStatus adds i to the "status" field.
func (nuo *NotificationUpdateOne) AddStatus(i int) *NotificationUpdateOne {
	nuo.mutation.AddStatus(i)
	return nuo
}

// SetLinks sets the "links" field.
func (nuo *NotificationUpdateOne) SetLinks(m []map[string]interface{}) *NotificationUpdateOne {
	nuo.mutation.SetLinks(m)
	return nuo
}

// AppendLinks appends m to the "links" field.
func (nuo *NotificationUpdateOne) AppendLinks(m []map[string]interface{}) *NotificationUpdateOne {
	nuo.mutation.AppendLinks(m)
	return nuo
}

// ClearLinks clears the value of the "links" field.
func (nuo *NotificationUpdateOne) ClearLinks() *NotificationUpdateOne {
	nuo.mutation.ClearLinks()
	return nuo
}

// SetChannelID sets the "channel_id" field.
func (nuo *NotificationUpdateOne) SetChannelID(s string) *NotificationUpdateOne {
	nuo.mutation.SetChannelID(s)
	return nuo
}

// SetNillableChannelID sets the "channel_id" field if the given value is not nil.
func (nuo *NotificationUpdateOne) SetNillableChannelID(s *string) *NotificationUpdateOne {
	if s != nil {
		nuo.SetChannelID(*s)
	}
	return nuo
}

// ClearChannelID clears the value of the "channel_id" field.
func (nuo *NotificationUpdateOne) ClearChannelID() *NotificationUpdateOne {
	nuo.mutation.ClearChannelID()
	return nuo
}

// SetUpdatedAt sets the "updated_at" field.
func (nuo *NotificationUpdateOne) SetUpdatedAt(i int64) *NotificationUpdateOne {
	nuo.mutation.ResetUpdatedAt()
	nuo.mutation.SetUpdatedAt(i)
	return nuo
}

// AddUpdatedAt adds i to the "updated_at" field.
func (nuo *NotificationUpdateOne) AddUpdatedAt(i int64) *NotificationUpdateOne {
	nuo.mutation.AddUpdatedAt(i)
	return nuo
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (nuo *NotificationUpdateOne) ClearUpdatedAt() *NotificationUpdateOne {
	nuo.mutation.ClearUpdatedAt()
	return nuo
}

// Mutation returns the NotificationMutation object of the builder.
func (nuo *NotificationUpdateOne) Mutation() *NotificationMutation {
	return nuo.mutation
}

// Where appends a list predicates to the NotificationUpdate builder.
func (nuo *NotificationUpdateOne) Where(ps ...predicate.Notification) *NotificationUpdateOne {
	nuo.mutation.Where(ps...)
	return nuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (nuo *NotificationUpdateOne) Select(field string, fields ...string) *NotificationUpdateOne {
	nuo.fields = append([]string{field}, fields...)
	return nuo
}

// Save executes the query and returns the updated Notification entity.
func (nuo *NotificationUpdateOne) Save(ctx context.Context) (*Notification, error) {
	nuo.defaults()
	return withHooks(ctx, nuo.sqlSave, nuo.mutation, nuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (nuo *NotificationUpdateOne) SaveX(ctx context.Context) *Notification {
	node, err := nuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (nuo *NotificationUpdateOne) Exec(ctx context.Context) error {
	_, err := nuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (nuo *NotificationUpdateOne) ExecX(ctx context.Context) {
	if err := nuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (nuo *NotificationUpdateOne) defaults() {
	if _, ok := nuo.mutation.UpdatedAt(); !ok && !nuo.mutation.UpdatedAtCleared() {
		v := notification.UpdateDefaultUpdatedAt()
		nuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (nuo *NotificationUpdateOne) check() error {
	if v, ok := nuo.mutation.UserID(); ok {
		if err := notification.UserIDValidator(v); err != nil {
			return &ValidationError{Name: "user_id", err: fmt.Errorf(`ent: validator failed for field "Notification.user_id": %w`, err)}
		}
	}
	if v, ok := nuo.mutation.ChannelID(); ok {
		if err := notification.ChannelIDValidator(v); err != nil {
			return &ValidationError{Name: "channel_id", err: fmt.Errorf(`ent: validator failed for field "Notification.channel_id": %w`, err)}
		}
	}
	return nil
}

func (nuo *NotificationUpdateOne) sqlSave(ctx context.Context) (_node *Notification, err error) {
	if err := nuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(notification.Table, notification.Columns, sqlgraph.NewFieldSpec(notification.FieldID, field.TypeString))
	id, ok := nuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Notification.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := nuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, notification.FieldID)
		for _, f := range fields {
			if !notification.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != notification.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := nuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := nuo.mutation.Title(); ok {
		_spec.SetField(notification.FieldTitle, field.TypeString, value)
	}
	if nuo.mutation.TitleCleared() {
		_spec.ClearField(notification.FieldTitle, field.TypeString)
	}
	if value, ok := nuo.mutation.Content(); ok {
		_spec.SetField(notification.FieldContent, field.TypeString, value)
	}
	if nuo.mutation.ContentCleared() {
		_spec.ClearField(notification.FieldContent, field.TypeString)
	}
	if value, ok := nuo.mutation.GetType(); ok {
		_spec.SetField(notification.FieldType, field.TypeString, value)
	}
	if nuo.mutation.TypeCleared() {
		_spec.ClearField(notification.FieldType, field.TypeString)
	}
	if value, ok := nuo.mutation.UserID(); ok {
		_spec.SetField(notification.FieldUserID, field.TypeString, value)
	}
	if nuo.mutation.UserIDCleared() {
		_spec.ClearField(notification.FieldUserID, field.TypeString)
	}
	if value, ok := nuo.mutation.Status(); ok {
		_spec.SetField(notification.FieldStatus, field.TypeInt, value)
	}
	if value, ok := nuo.mutation.AddedStatus(); ok {
		_spec.AddField(notification.FieldStatus, field.TypeInt, value)
	}
	if value, ok := nuo.mutation.Links(); ok {
		_spec.SetField(notification.FieldLinks, field.TypeJSON, value)
	}
	if value, ok := nuo.mutation.AppendedLinks(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, notification.FieldLinks, value)
		})
	}
	if nuo.mutation.LinksCleared() {
		_spec.ClearField(notification.FieldLinks, field.TypeJSON)
	}
	if value, ok := nuo.mutation.ChannelID(); ok {
		_spec.SetField(notification.FieldChannelID, field.TypeString, value)
	}
	if nuo.mutation.ChannelIDCleared() {
		_spec.ClearField(notification.FieldChannelID, field.TypeString)
	}
	if nuo.mutation.CreatedAtCleared() {
		_spec.ClearField(notification.FieldCreatedAt, field.TypeInt64)
	}
	if value, ok := nuo.mutation.UpdatedAt(); ok {
		_spec.SetField(notification.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := nuo.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(notification.FieldUpdatedAt, field.TypeInt64, value)
	}
	if nuo.mutation.UpdatedAtCleared() {
		_spec.ClearField(notification.FieldUpdatedAt, field.TypeInt64)
	}
	_node = &Notification{config: nuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, nuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{notification.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	nuo.mutation.done = true
	return _node, nil
}
