// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ncobase/workflow/data/ent/delegation"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// DelegationCreate is the builder for creating a Delegation entity.
type DelegationCreate struct {
	config
	mutation *DelegationMutation
	hooks    []Hook
}

// SetStatus sets the "status" field.
func (_c *DelegationCreate) SetStatus(v string) *DelegationCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *DelegationCreate) SetNillableStatus(v *string) *DelegationCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetExtras sets the "extras" field.
func (_c *DelegationCreate) SetExtras(v map[string]interface{}) *DelegationCreate {
	_c.mutation.SetExtras(v)
	return _c
}

// SetSpaceID sets the "space_id" field.
func (_c *DelegationCreate) SetSpaceID(v string) *DelegationCreate {
	_c.mutation.SetSpaceID(v)
	return _c
}

// SetNillableSpaceID sets the "space_id" field if the given value is not nil.
func (_c *DelegationCreate) SetNillableSpaceID(v *string) *DelegationCreate {
	if v != nil {
		_c.SetSpaceID(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *DelegationCreate) SetCreatedBy(v string) *DelegationCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *DelegationCreate) SetNillableCreatedBy(v *string) *DelegationCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *DelegationCreate) SetUpdatedBy(v string) *DelegationCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *DelegationCreate) SetNillableUpdatedBy(v *string) *DelegationCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *DelegationCreate) SetCreatedAt(v int64) *DelegationCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DelegationCreate) SetNillableCreatedAt(v *int64) *DelegationCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DelegationCreate) SetUpdatedAt(v int64) *DelegationCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DelegationCreate) SetNillableUpdatedAt(v *int64) *DelegationCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDelegatorID sets the "delegator_id" field.
func (_c *DelegationCreate) SetDelegatorID(v string) *DelegationCreate {
	_c.mutation.SetDelegatorID(v)
	return _c
}

// SetDelegateeID sets the "delegatee_id" field.
func (_c *DelegationCreate) SetDelegateeID(v string) *DelegationCreate {
	_c.mutation.SetDelegateeID(v)
	return _c
}

// SetTemplateID sets the "template_id" field.
func (_c *DelegationCreate) SetTemplateID(v string) *DelegationCreate {
	_c.mutation.SetTemplateID(v)
	return _c
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_c *DelegationCreate) SetNillableTemplateID(v *string) *DelegationCreate {
	if v != nil {
		_c.SetTemplateID(*v)
	}
	return _c
}

// SetNodeType sets the "node_type" field.
func (_c *DelegationCreate) SetNodeType(v string) *DelegationCreate {
	_c.mutation.SetNodeType(v)
	return _c
}

// SetNillableNodeType sets the "node_type" field if the given value is not nil.
func (_c *DelegationCreate) SetNillableNodeType(v *string) *DelegationCreate {
	if v != nil {
		_c.SetNodeType(*v)
	}
	return _c
}

// SetConditions sets the "conditions" field.
func (_c *DelegationCreate) SetConditions(v []string) *DelegationCreate {
	_c.mutation.SetConditions(v)
	return _c
}

// SetStartTime sets the "start_time" field.
func (_c *DelegationCreate) SetStartTime(v int64) *DelegationCreate {
	_c.mutation.SetStartTime(v)
	return _c
}

// SetEndTime sets the "end_time" field.
func (_c *DelegationCreate) SetEndTime(v int64) *DelegationCreate {
	_c.mutation.SetEndTime(v)
	return _c
}

// SetIsEnabled sets the "is_enabled" field.
func (_c *DelegationCreate) SetIsEnabled(v bool) *DelegationCreate {
	_c.mutation.SetIsEnabled(v)
	return _c
}

// SetNillableIsEnabled sets the "is_enabled" field if the given value is not nil.
func (_c *DelegationCreate) SetNillableIsEnabled(v *bool) *DelegationCreate {
	if v != nil {
		_c.SetIsEnabled(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *DelegationCreate) SetID(v string) *DelegationCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *DelegationCreate) SetNillableID(v *string) *DelegationCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the DelegationMutation object of the builder.
func (_c *DelegationCreate) Mutation() *DelegationMutation {
	return _c.mutation
}

// Save creates the Delegation in the database.
func (_c *DelegationCreate) Save(ctx context.Context) (*Delegation, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DelegationCreate) SaveX(ctx context.Context) *Delegation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DelegationCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DelegationCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DelegationCreate) defaults() {
	if _, ok := _c.mutation.Extras(); !ok {
		v := delegation.DefaultExtras
		_c.mutation.SetExtras(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := delegation.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := delegation.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsEnabled(); !ok {
		v := delegation.DefaultIsEnabled
		_c.mutation.SetIsEnabled(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := delegation.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DelegationCreate) check() error {
	if _, ok := _c.mutation.DelegatorID(); !ok {
		return &ValidationError{Name: "delegator_id", err: errors.New(`ent: missing required field "Delegation.delegator_id"`)}
	}
	if _, ok := _c.mutation.DelegateeID(); !ok {
		return &ValidationError{Name: "delegatee_id", err: errors.New(`ent: missing required field "Delegation.delegatee_id"`)}
	}
	if _, ok := _c.mutation.StartTime(); !ok {
		return &ValidationError{Name: "start_time", err: errors.New(`ent: missing required field "Delegation.start_time"`)}
	}
	if _, ok := _c.mutation.EndTime(); !ok {
		return &ValidationError{Name: "end_time", err: errors.New(`ent: missing required field "Delegation.end_time"`)}
	}
	if _, ok := _c.mutation.IsEnabled(); !ok {
		return &ValidationError{Name: "is_enabled", err: errors.New(`ent: missing required field "Delegation.is_enabled"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := delegation.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "Delegation.id": %w`, err)}
		}
	}
	return nil
}

func (_c *DelegationCreate) sqlSave(ctx context.Context) (*Delegation, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected Delegation.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DelegationCreate) createSpec() (*Delegation, *sqlgraph.CreateSpec) {
	var (
		_node = &Delegation{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(delegation.Table, sqlgraph.NewFieldSpec(delegation.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(delegation.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Extras(); ok {
		_spec.SetField(delegation.FieldExtras, field.TypeJSON, value)
		_node.Extras = value
	}
	if value, ok := _c.mutation.SpaceID(); ok {
		_spec.SetField(delegation.FieldSpaceID, field.TypeString, value)
		_node.SpaceID = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(delegation.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(delegation.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(delegation.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(delegation.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DelegatorID(); ok {
		_spec.SetField(delegation.FieldDelegatorID, field.TypeString, value)
		_node.DelegatorID = value
	}
	if value, ok := _c.mutation.DelegateeID(); ok {
		_spec.SetField(delegation.FieldDelegateeID, field.TypeString, value)
		_node.DelegateeID = value
	}
	if value, ok := _c.mutation.TemplateID(); ok {
		_spec.SetField(delegation.FieldTemplateID, field.TypeString, value)
		_node.TemplateID = value
	}
	if value, ok := _c.mutation.NodeType(); ok {
		_spec.SetField(delegation.FieldNodeType, field.TypeString, value)
		_node.NodeType = value
	}
	if value, ok := _c.mutation.Conditions(); ok {
		_spec.SetField(delegation.FieldConditions, field.TypeJSON, value)
		_node.Conditions = value
	}
	if value, ok := _c.mutation.StartTime(); ok {
		_spec.SetField(delegation.FieldStartTime, field.TypeInt64, value)
		_node.StartTime = value
	}
	if value, ok := _c.mutation.EndTime(); ok {
		_spec.SetField(delegation.FieldEndTime, field.TypeInt64, value)
		_node.EndTime = value
	}
	if value, ok := _c.mutation.IsEnabled(); ok {
		_spec.SetField(delegation.FieldIsEnabled, field.TypeBool, value)
		_node.IsEnabled = value
	}
	return _node, _spec
}

// DelegationCreateBulk is the builder for creating many Delegation entities in bulk.
type DelegationCreateBulk struct {
	config
	err      error
	builders []*DelegationCreate
}

// Save creates the Delegation entities in the database.
func (_c *DelegationCreateBulk) Save(ctx context.Context) ([]*Delegation, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Delegation, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DelegationMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DelegationCreateBulk) SaveX(ctx context.Context) []*Delegation {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DelegationCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DelegationCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
