// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ncobase/workflow/data/ent/predicate"
	"ncobase/workflow/data/ent/process"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// ProcessUpdate is the builder for updating Process entities.
type ProcessUpdate struct {
	config
	hooks    []Hook
	mutation *ProcessMutation
}

// Where appends a list predicates to the ProcessUpdate builder.
func (_u *ProcessUpdate) Where(ps ...predicate.Process) *ProcessUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProcessUpdate) SetStatus(v string) *ProcessUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableStatus(v *string) *ProcessUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *ProcessUpdate) ClearStatus() *ProcessUpdate {
	_u.mutation.ClearStatus()
	return _u
}

// SetProcessID sets the "process_id" field.
func (_u *ProcessUpdate) SetProcessID(v string) *ProcessUpdate {
	_u.mutation.SetProcessID(v)
	return _u
}

// SetNillableProcessID sets the "process_id" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableProcessID(v *string) *ProcessUpdate {
	if v != nil {
		_u.SetProcessID(*v)
	}
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *ProcessUpdate) SetTemplateID(v string) *ProcessUpdate {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableTemplateID(v *string) *ProcessUpdate {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// SetBusinessKey sets the "business_key" field.
func (_u *ProcessUpdate) SetBusinessKey(v string) *ProcessUpdate {
	_u.mutation.SetBusinessKey(v)
	return _u
}

// SetNillableBusinessKey sets the "business_key" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableBusinessKey(v *string) *ProcessUpdate {
	if v != nil {
		_u.SetBusinessKey(*v)
	}
	return _u
}

// SetFormCode sets the "form_code" field.
func (_u *ProcessUpdate) SetFormCode(v string) *ProcessUpdate {
	_u.mutation.SetFormCode(v)
	return _u
}

// SetNillableFormCode sets the "form_code" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableFormCode(v *string) *ProcessUpdate {
	if v != nil {
		_u.SetFormCode(*v)
	}
	return _u
}

// SetFormVersion sets the "form_version" field.
func (_u *ProcessUpdate) SetFormVersion(v string) *ProcessUpdate {
	_u.mutation.SetFormVersion(v)
	return _u
}

// SetNillableFormVersion sets the "form_version" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableFormVersion(v *string) *ProcessUpdate {
	if v != nil {
		_u.SetFormVersion(*v)
	}
	return _u
}

// ClearFormVersion clears the value of the "form_version" field.
func (_u *ProcessUpdate) ClearFormVersion() *ProcessUpdate {
	_u.mutation.ClearFormVersion()
	return _u
}

// SetFormConfig sets the "form_config" field.
func (_u *ProcessUpdate) SetFormConfig(v map[string]interface{}) *ProcessUpdate {
	_u.mutation.SetFormConfig(v)
	return _u
}

// ClearFormConfig clears the value of the "form_config" field.
func (_u *ProcessUpdate) ClearFormConfig() *ProcessUpdate {
	_u.mutation.ClearFormConfig()
	return _u
}

// SetFormPermissions sets the "form_permissions" field.
func (_u *ProcessUpdate) SetFormPermissions(v map[string]interface{}) *ProcessUpdate {
	_u.mutation.SetFormPermissions(v)
	return _u
}

// ClearFormPermissions clears the value of the "form_permissions" field.
func (_u *ProcessUpdate) ClearFormPermissions() *ProcessUpdate {
	_u.mutation.ClearFormPermissions()
	return _u
}

// SetFieldPermissions sets the "field_permissions" field.
func (_u *ProcessUpdate) SetFieldPermissions(v map[string]interface{}) *ProcessUpdate {
	_u.mutation.SetFieldPermissions(v)
	return _u
}

// ClearFieldPermissions clears the value of the "field_permissions" field.
func (_u *ProcessUpdate) ClearFieldPermissions() *ProcessUpdate {
	_u.mutation.ClearFieldPermissions()
	return _u
}

// SetBusinessTags sets the "business_tags" field.
func (_u *ProcessUpdate) SetBusinessTags(v []string) *ProcessUpdate {
	_u.mutation.SetBusinessTags(v)
	return _u
}

// AppendBusinessTags appends value to the "business_tags" field.
func (_u *ProcessUpdate) AppendBusinessTags(v []string) *ProcessUpdate {
	_u.mutation.AppendBusinessTags(v)
	return _u
}

// ClearBusinessTags clears the value of the "business_tags" field.
func (_u *ProcessUpdate) ClearBusinessTags() *ProcessUpdate {
	_u.mutation.ClearBusinessTags()
	return _u
}

// SetModuleCode sets the "module_code" field.
func (_u *ProcessUpdate) SetModuleCode(v string) *ProcessUpdate {
	_u.mutation.SetModuleCode(v)
	return _u
}

// SetNillableModuleCode sets the "module_code" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableModuleCode(v *string) *ProcessUpdate {
	if v != nil {
		_u.SetModuleCode(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *ProcessUpdate) SetCategory(v string) *ProcessUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableCategory(v *string) *ProcessUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *ProcessUpdate) ClearCategory() *ProcessUpdate {
	_u.mutation.ClearCategory()
	return _u
}

// SetFlowStatus sets the "flow_status" field.
func (_u *ProcessUpdate) SetFlowStatus(v string) *ProcessUpdate {
	_u.mutation.SetFlowStatus(v)
	return _u
}

// SetNillableFlowStatus sets the "flow_status" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableFlowStatus(v *string) *ProcessUpdate {
	if v != nil {
		_u.SetFlowStatus(*v)
	}
	return _u
}

// ClearFlowStatus clears the value of the "flow_status" field.
func (_u *ProcessUpdate) ClearFlowStatus() *ProcessUpdate {
	_u.mutation.ClearFlowStatus()
	return _u
}

// SetFlowVariables sets the "flow_variables" field.
func (_u *ProcessUpdate) SetFlowVariables(v map[string]interface{}) *ProcessUpdate {
	_u.mutation.SetFlowVariables(v)
	return _u
}

// ClearFlowVariables clears the value of the "flow_variables" field.
func (_u *ProcessUpdate) ClearFlowVariables() *ProcessUpdate {
	_u.mutation.ClearFlowVariables()
	return _u
}

// SetIsDraft sets the "is_draft" field.
func (_u *ProcessUpdate) SetIsDraft(v bool) *ProcessUpdate {
	_u.mutation.SetIsDraft(v)
	return _u
}

// SetNillableIsDraft sets the "is_draft" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableIsDraft(v *bool) *ProcessUpdate {
	if v != nil {
		_u.SetIsDraft(*v)
	}
	return _u
}

// SetIsTerminated sets the "is_terminated" field.
func (_u *ProcessUpdate) SetIsTerminated(v bool) *ProcessUpdate {
	_u.mutation.SetIsTerminated(v)
	return _u
}

// SetNillableIsTerminated sets the "is_terminated" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableIsTerminated(v *bool) *ProcessUpdate {
	if v != nil {
		_u.SetIsTerminated(*v)
	}
	return _u
}

// SetIsSuspended sets the "is_suspended" field.
func (_u *ProcessUpdate) SetIsSuspended(v bool) *ProcessUpdate {
	_u.mutation.SetIsSuspended(v)
	return _u
}

// SetNillableIsSuspended sets the "is_suspended" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableIsSuspended(v *bool) *ProcessUpdate {
	if v != nil {
		_u.SetIsSuspended(*v)
	}
	return _u
}

// SetSuspendReason sets the "suspend_reason" field.
func (_u *ProcessUpdate) SetSuspendReason(v string) *ProcessUpdate {
	_u.mutation.SetSuspendReason(v)
	return _u
}

// SetNillableSuspendReason sets the "suspend_reason" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableSuspendReason(v *string) *ProcessUpdate {
	if v != nil {
		_u.SetSuspendReason(*v)
	}
	return _u
}

// ClearSuspendReason clears the value of the "suspend_reason" field.
func (_u *ProcessUpdate) ClearSuspendReason() *ProcessUpdate {
	_u.mutation.ClearSuspendReason()
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *ProcessUpdate) SetStartTime(v int64) *ProcessUpdate {
	_u.mutation.ResetStartTime()
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableStartTime(v *int64) *ProcessUpdate {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// AddStartTime adds value to the "start_time" field.
func (_u *ProcessUpdate) AddStartTime(v int64) *ProcessUpdate {
	_u.mutation.AddStartTime(v)
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *ProcessUpdate) SetEndTime(v int64) *ProcessUpdate {
	_u.mutation.ResetEndTime()
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableEndTime(v *int64) *ProcessUpdate {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// AddEndTime adds value to the "end_time" field.
func (_u *ProcessUpdate) AddEndTime(v int64) *ProcessUpdate {
	_u.mutation.AddEndTime(v)
	return _u
}

// ClearEndTime clears the value of the "end_time" field.
func (_u *ProcessUpdate) ClearEndTime() *ProcessUpdate {
	_u.mutation.ClearEndTime()
	return _u
}

// SetDueTime sets the "due_time" field.
func (_u *ProcessUpdate) SetDueTime(v int64) *ProcessUpdate {
	_u.mutation.ResetDueTime()
	_u.mutation.SetDueTime(v)
	return _u
}

// SetNillableDueTime sets the "due_time" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableDueTime(v *int64) *ProcessUpdate {
	if v != nil {
		_u.SetDueTime(*v)
	}
	return _u
}

// AddDueTime adds value to the "due_time" field.
func (_u *ProcessUpdate) AddDueTime(v int64) *ProcessUpdate {
	_u.mutation.AddDueTime(v)
	return _u
}

// ClearDueTime clears the value of the "due_time" field.
func (_u *ProcessUpdate) ClearDueTime() *ProcessUpdate {
	_u.mutation.ClearDueTime()
	return _u
}

// SetDuration sets the "duration" field.
func (_u *ProcessUpdate) SetDuration(v int) *ProcessUpdate {
	_u.mutation.ResetDuration()
	_u.mutation.SetDuration(v)
	return _u
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableDuration(v *int) *ProcessUpdate {
	if v != nil {
		_u.SetDuration(*v)
	}
	return _u
}

// AddDuration adds value to the "duration" field.
func (_u *ProcessUpdate) AddDuration(v int) *ProcessUpdate {
	_u.mutation.AddDuration(v)
	return _u
}

// ClearDuration clears the value of the "duration" field.
func (_u *ProcessUpdate) ClearDuration() *ProcessUpdate {
	_u.mutation.ClearDuration()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *ProcessUpdate) SetPriority(v int) *ProcessUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillablePriority(v *int) *ProcessUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *ProcessUpdate) AddPriority(v int) *ProcessUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetIsTimeout sets the "is_timeout" field.
func (_u *ProcessUpdate) SetIsTimeout(v bool) *ProcessUpdate {
	_u.mutation.SetIsTimeout(v)
	return _u
}

// SetNillableIsTimeout sets the "is_timeout" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableIsTimeout(v *bool) *ProcessUpdate {
	if v != nil {
		_u.SetIsTimeout(*v)
	}
	return _u
}

// SetReminderCount sets the "reminder_count" field.
func (_u *ProcessUpdate) SetReminderCount(v int) *ProcessUpdate {
	_u.mutation.ResetReminderCount()
	_u.mutation.SetReminderCount(v)
	return _u
}

// SetNillableReminderCount sets the "reminder_count" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableReminderCount(v *int) *ProcessUpdate {
	if v != nil {
		_u.SetReminderCount(*v)
	}
	return _u
}

// AddReminderCount adds value to the "reminder_count" field.
func (_u *ProcessUpdate) AddReminderCount(v int) *ProcessUpdate {
	_u.mutation.AddReminderCount(v)
	return _u
}

// SetAllowCancel sets the "allow_cancel" field.
func (_u *ProcessUpdate) SetAllowCancel(v bool) *ProcessUpdate {
	_u.mutation.SetAllowCancel(v)
	return _u
}

// SetNillableAllowCancel sets the "allow_cancel" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableAllowCancel(v *bool) *ProcessUpdate {
	if v != nil {
		_u.SetAllowCancel(*v)
	}
	return _u
}

// SetAllowUrge sets the "allow_urge" field.
func (_u *ProcessUpdate) SetAllowUrge(v bool) *ProcessUpdate {
	_u.mutation.SetAllowUrge(v)
	return _u
}

// SetNillableAllowUrge sets the "allow_urge" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableAllowUrge(v *bool) *ProcessUpdate {
	if v != nil {
		_u.SetAllowUrge(*v)
	}
	return _u
}

// SetAllowDelegate sets the "allow_delegate" field.
func (_u *ProcessUpdate) SetAllowDelegate(v bool) *ProcessUpdate {
	_u.mutation.SetAllowDelegate(v)
	return _u
}

// SetNillableAllowDelegate sets the "allow_delegate" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableAllowDelegate(v *bool) *ProcessUpdate {
	if v != nil {
		_u.SetAllowDelegate(*v)
	}
	return _u
}

// SetAllowTransfer sets the "allow_transfer" field.
func (_u *ProcessUpdate) SetAllowTransfer(v bool) *ProcessUpdate {
	_u.mutation.SetAllowTransfer(v)
	return _u
}

// SetNillableAllowTransfer sets the "allow_transfer" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableAllowTransfer(v *bool) *ProcessUpdate {
	if v != nil {
		_u.SetAllowTransfer(*v)
	}
	return _u
}

// SetIsDraftEnabled sets the "is_draft_enabled" field.
func (_u *ProcessUpdate) SetIsDraftEnabled(v bool) *ProcessUpdate {
	_u.mutation.SetIsDraftEnabled(v)
	return _u
}

// SetNillableIsDraftEnabled sets the "is_draft_enabled" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableIsDraftEnabled(v *bool) *ProcessUpdate {
	if v != nil {
		_u.SetIsDraftEnabled(*v)
	}
	return _u
}

// SetIsAutoStart sets the "is_auto_start" field.
func (_u *ProcessUpdate) SetIsAutoStart(v bool) *ProcessUpdate {
	_u.mutation.SetIsAutoStart(v)
	return _u
}

// SetNillableIsAutoStart sets the "is_auto_start" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableIsAutoStart(v *bool) *ProcessUpdate {
	if v != nil {
		_u.SetIsAutoStart(*v)
	}
	return _u
}

// SetStrictMode sets the "strict_mode" field.
func (_u *ProcessUpdate) SetStrictMode(v bool) *ProcessUpdate {
	_u.mutation.SetStrictMode(v)
	return _u
}

// SetNillableStrictMode sets the "strict_mode" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableStrictMode(v *bool) *ProcessUpdate {
	if v != nil {
		_u.SetStrictMode(*v)
	}
	return _u
}

// SetExtras sets the "extras" field.
func (_u *ProcessUpdate) SetExtras(v map[string]interface{}) *ProcessUpdate {
	_u.mutation.SetExtras(v)
	return _u
}

// ClearExtras clears the value of the "extras" field.
func (_u *ProcessUpdate) ClearExtras() *ProcessUpdate {
	_u.mutation.ClearExtras()
	return _u
}

// SetSpaceID sets the "space_id" field.
func (_u *ProcessUpdate) SetSpaceID(v string) *ProcessUpdate {
	_u.mutation.SetSpaceID(v)
	return _u
}

// SetNillableSpaceID sets the "space_id" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableSpaceID(v *string) *ProcessUpdate {
	if v != nil {
		_u.SetSpaceID(*v)
	}
	return _u
}

// ClearSpaceID clears the value of the "space_id" field.
func (_u *ProcessUpdate) ClearSpaceID() *ProcessUpdate {
	_u.mutation.ClearSpaceID()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ProcessUpdate) SetCreatedBy(v string) *ProcessUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableCreatedBy(v *string) *ProcessUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ProcessUpdate) ClearCreatedBy() *ProcessUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ProcessUpdate) SetUpdatedBy(v string) *ProcessUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableUpdatedBy(v *string) *ProcessUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ProcessUpdate) ClearUpdatedBy() *ProcessUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProcessUpdate) SetUpdatedAt(v int64) *ProcessUpdate {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *ProcessUpdate) AddUpdatedAt(v int64) *ProcessUpdate {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ProcessUpdate) ClearUpdatedAt() *ProcessUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetProcessKey sets the "process_key" field.
func (_u *ProcessUpdate) SetProcessKey(v string) *ProcessUpdate {
	_u.mutation.SetProcessKey(v)
	return _u
}

// SetNillableProcessKey sets the "process_key" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableProcessKey(v *string) *ProcessUpdate {
	if v != nil {
		_u.SetProcessKey(*v)
	}
	return _u
}

// SetInitiator sets the "initiator" field.
func (_u *ProcessUpdate) SetInitiator(v string) *ProcessUpdate {
	_u.mutation.SetInitiator(v)
	return _u
}

// SetNillableInitiator sets the "initiator" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableInitiator(v *string) *ProcessUpdate {
	if v != nil {
		_u.SetInitiator(*v)
	}
	return _u
}

// SetInitiatorDept sets the "initiator_dept" field.
func (_u *ProcessUpdate) SetInitiatorDept(v string) *ProcessUpdate {
	_u.mutation.SetInitiatorDept(v)
	return _u
}

// SetNillableInitiatorDept sets the "initiator_dept" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableInitiatorDept(v *string) *ProcessUpdate {
	if v != nil {
		_u.SetInitiatorDept(*v)
	}
	return _u
}

// ClearInitiatorDept clears the value of the "initiator_dept" field.
func (_u *ProcessUpdate) ClearInitiatorDept() *ProcessUpdate {
	_u.mutation.ClearInitiatorDept()
	return _u
}

// SetProcessCode sets the "process_code" field.
func (_u *ProcessUpdate) SetProcessCode(v string) *ProcessUpdate {
	_u.mutation.SetProcessCode(v)
	return _u
}

// SetNillableProcessCode sets the "process_code" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableProcessCode(v *string) *ProcessUpdate {
	if v != nil {
		_u.SetProcessCode(*v)
	}
	return _u
}

// SetVariables sets the "variables" field.
func (_u *ProcessUpdate) SetVariables(v map[string]interface{}) *ProcessUpdate {
	_u.mutation.SetVariables(v)
	return _u
}

// SetCurrentNode sets the "current_node" field.
func (_u *ProcessUpdate) SetCurrentNode(v string) *ProcessUpdate {
	_u.mutation.SetCurrentNode(v)
	return _u
}

// SetNillableCurrentNode sets the "current_node" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableCurrentNode(v *string) *ProcessUpdate {
	if v != nil {
		_u.SetCurrentNode(*v)
	}
	return _u
}

// ClearCurrentNode clears the value of the "current_node" field.
func (_u *ProcessUpdate) ClearCurrentNode() *ProcessUpdate {
	_u.mutation.ClearCurrentNode()
	return _u
}

// SetActiveNodes sets the "active_nodes" field.
func (_u *ProcessUpdate) SetActiveNodes(v []string) *ProcessUpdate {
	_u.mutation.SetActiveNodes(v)
	return _u
}

// AppendActiveNodes appends value to the "active_nodes" field.
func (_u *ProcessUpdate) AppendActiveNodes(v []string) *ProcessUpdate {
	_u.mutation.AppendActiveNodes(v)
	return _u
}

// ClearActiveNodes clears the value of the "active_nodes" field.
func (_u *ProcessUpdate) ClearActiveNodes() *ProcessUpdate {
	_u.mutation.ClearActiveNodes()
	return _u
}

// SetProcessSnapshot sets the "process_snapshot" field.
func (_u *ProcessUpdate) SetProcessSnapshot(v map[string]interface{}) *ProcessUpdate {
	_u.mutation.SetProcessSnapshot(v)
	return _u
}

// ClearProcessSnapshot clears the value of the "process_snapshot" field.
func (_u *ProcessUpdate) ClearProcessSnapshot() *ProcessUpdate {
	_u.mutation.ClearProcessSnapshot()
	return _u
}

// SetFormSnapshot sets the "form_snapshot" field.
func (_u *ProcessUpdate) SetFormSnapshot(v map[string]interface{}) *ProcessUpdate {
	_u.mutation.SetFormSnapshot(v)
	return _u
}

// ClearFormSnapshot clears the value of the "form_snapshot" field.
func (_u *ProcessUpdate) ClearFormSnapshot() *ProcessUpdate {
	_u.mutation.ClearFormSnapshot()
	return _u
}

// SetUrgeCount sets the "urge_count" field.
func (_u *ProcessUpdate) SetUrgeCount(v int) *ProcessUpdate {
	_u.mutation.ResetUrgeCount()
	_u.mutation.SetUrgeCount(v)
	return _u
}

// SetNillableUrgeCount sets the "urge_count" field if the given value is not nil.
func (_u *ProcessUpdate) SetNillableUrgeCount(v *int) *ProcessUpdate {
	if v != nil {
		_u.SetUrgeCount(*v)
	}
	return _u
}

// AddUrgeCount adds value to the "urge_count" field.
func (_u *ProcessUpdate) AddUrgeCount(v int) *ProcessUpdate {
	_u.mutation.AddUrgeCount(v)
	return _u
}

// Mutation returns the ProcessMutation object of the builder.
func (_u *ProcessUpdate) Mutation() *ProcessMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProcessUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProcessUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProcessUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProcessUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProcessUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := process.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ProcessUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(process.Table, process.Columns, sqlgraph.NewFieldSpec(process.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(process.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(process.FieldStatus, field.TypeString)
	}
	if value, ok := _u.mutation.ProcessID(); ok {
		_spec.SetField(process.FieldProcessID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TemplateID(); ok {
		_spec.SetField(process.FieldTemplateID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BusinessKey(); ok {
		_spec.SetField(process.FieldBusinessKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.FormCode(); ok {
		_spec.SetField(process.FieldFormCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.FormVersion(); ok {
		_spec.SetField(process.FieldFormVersion, field.TypeString, value)
	}
	if _u.mutation.FormVersionCleared() {
		_spec.ClearField(process.FieldFormVersion, field.TypeString)
	}
	if value, ok := _u.mutation.FormConfig(); ok {
		_spec.SetField(process.FieldFormConfig, field.TypeJSON, value)
	}
	if _u.mutation.FormConfigCleared() {
		_spec.ClearField(process.FieldFormConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.FormPermissions(); ok {
		_spec.SetField(process.FieldFormPermissions, field.TypeJSON, value)
	}
	if _u.mutation.FormPermissionsCleared() {
		_spec.ClearField(process.FieldFormPermissions, field.TypeJSON)
	}
	if value, ok := _u.mutation.FieldPermissions(); ok {
		_spec.SetField(process.FieldFieldPermissions, field.TypeJSON, value)
	}
	if _u.mutation.FieldPermissionsCleared() {
		_spec.ClearField(process.FieldFieldPermissions, field.TypeJSON)
	}
	if value, ok := _u.mutation.BusinessTags(); ok {
		_spec.SetField(process.FieldBusinessTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBusinessTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, process.FieldBusinessTags, value)
		})
	}
	if _u.mutation.BusinessTagsCleared() {
		_spec.ClearField(process.FieldBusinessTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.ModuleCode(); ok {
		_spec.SetField(process.FieldModuleCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(process.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(process.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.FlowStatus(); ok {
		_spec.SetField(process.FieldFlowStatus, field.TypeString, value)
	}
	if _u.mutation.FlowStatusCleared() {
		_spec.ClearField(process.FieldFlowStatus, field.TypeString)
	}
	if value, ok := _u.mutation.FlowVariables(); ok {
		_spec.SetField(process.FieldFlowVariables, field.TypeJSON, value)
	}
	if _u.mutation.FlowVariablesCleared() {
		_spec.ClearField(process.FieldFlowVariables, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsDraft(); ok {
		_spec.SetField(process.FieldIsDraft, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsTerminated(); ok {
		_spec.SetField(process.FieldIsTerminated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsSuspended(); ok {
		_spec.SetField(process.FieldIsSuspended, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SuspendReason(); ok {
		_spec.SetField(process.FieldSuspendReason, field.TypeString, value)
	}
	if _u.mutation.SuspendReasonCleared() {
		_spec.ClearField(process.FieldSuspendReason, field.TypeString)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(process.FieldStartTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStartTime(); ok {
		_spec.AddField(process.FieldStartTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(process.FieldEndTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEndTime(); ok {
		_spec.AddField(process.FieldEndTime, field.TypeInt64, value)
	}
	if _u.mutation.EndTimeCleared() {
		_spec.ClearField(process.FieldEndTime, field.TypeInt64)
	}
	if value, ok := _u.mutation.DueTime(); ok {
		_spec.SetField(process.FieldDueTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDueTime(); ok {
		_spec.AddField(process.FieldDueTime, field.TypeInt64, value)
	}
	if _u.mutation.DueTimeCleared() {
		_spec.ClearField(process.FieldDueTime, field.TypeInt64)
	}
	if value, ok := _u.mutation.Duration(); ok {
		_spec.SetField(process.FieldDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDuration(); ok {
		_spec.AddField(process.FieldDuration, field.TypeInt, value)
	}
	if _u.mutation.DurationCleared() {
		_spec.ClearField(process.FieldDuration, field.TypeInt)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(process.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(process.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsTimeout(); ok {
		_spec.SetField(process.FieldIsTimeout, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ReminderCount(); ok {
		_spec.SetField(process.FieldReminderCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReminderCount(); ok {
		_spec.AddField(process.FieldReminderCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AllowCancel(); ok {
		_spec.SetField(process.FieldAllowCancel, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowUrge(); ok {
		_spec.SetField(process.FieldAllowUrge, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowDelegate(); ok {
		_spec.SetField(process.FieldAllowDelegate, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowTransfer(); ok {
		_spec.SetField(process.FieldAllowTransfer, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsDraftEnabled(); ok {
		_spec.SetField(process.FieldIsDraftEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsAutoStart(); ok {
		_spec.SetField(process.FieldIsAutoStart, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StrictMode(); ok {
		_spec.SetField(process.FieldStrictMode, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Extras(); ok {
		_spec.SetField(process.FieldExtras, field.TypeJSON, value)
	}
	if _u.mutation.ExtrasCleared() {
		_spec.ClearField(process.FieldExtras, field.TypeJSON)
	}
	if value, ok := _u.mutation.SpaceID(); ok {
		_spec.SetField(process.FieldSpaceID, field.TypeString, value)
	}
	if _u.mutation.SpaceIDCleared() {
		_spec.ClearField(process.FieldSpaceID, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(process.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(process.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(process.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(process.FieldUpdatedBy, field.TypeString)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(process.FieldCreatedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(process.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(process.FieldUpdatedAt, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(process.FieldUpdatedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.ProcessKey(); ok {
		_spec.SetField(process.FieldProcessKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Initiator(); ok {
		_spec.SetField(process.FieldInitiator, field.TypeString, value)
	}
	if value, ok := _u.mutation.InitiatorDept(); ok {
		_spec.SetField(process.FieldInitiatorDept, field.TypeString, value)
	}
	if _u.mutation.InitiatorDeptCleared() {
		_spec.ClearField(process.FieldInitiatorDept, field.TypeString)
	}
	if value, ok := _u.mutation.ProcessCode(); ok {
		_spec.SetField(process.FieldProcessCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Variables(); ok {
		_spec.SetField(process.FieldVariables, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CurrentNode(); ok {
		_spec.SetField(process.FieldCurrentNode, field.TypeString, value)
	}
	if _u.mutation.CurrentNodeCleared() {
		_spec.ClearField(process.FieldCurrentNode, field.TypeString)
	}
	if value, ok := _u.mutation.ActiveNodes(); ok {
		_spec.SetField(process.FieldActiveNodes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedActiveNodes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, process.FieldActiveNodes, value)
		})
	}
	if _u.mutation.ActiveNodesCleared() {
		_spec.ClearField(process.FieldActiveNodes, field.TypeJSON)
	}
	if value, ok := _u.mutation.ProcessSnapshot(); ok {
		_spec.SetField(process.FieldProcessSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.ProcessSnapshotCleared() {
		_spec.ClearField(process.FieldProcessSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.FormSnapshot(); ok {
		_spec.SetField(process.FieldFormSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.FormSnapshotCleared() {
		_spec.ClearField(process.FieldFormSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.UrgeCount(); ok {
		_spec.SetField(process.FieldUrgeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUrgeCount(); ok {
		_spec.AddField(process.FieldUrgeCount, field.TypeInt, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{process.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProcessUpdateOne is the builder for updating a single Process entity.
type ProcessUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProcessMutation
}

// SetStatus sets the "status" field.
func (_u *ProcessUpdateOne) SetStatus(v string) *ProcessUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableStatus(v *string) *ProcessUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// ClearStatus clears the value of the "status" field.
func (_u *ProcessUpdateOne) ClearStatus() *ProcessUpdateOne {
	_u.mutation.ClearStatus()
	return _u
}

// SetProcessID sets the "process_id" field.
func (_u *ProcessUpdateOne) SetProcessID(v string) *ProcessUpdateOne {
	_u.mutation.SetProcessID(v)
	return _u
}

// SetNillableProcessID sets the "process_id" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableProcessID(v *string) *ProcessUpdateOne {
	if v != nil {
		_u.SetProcessID(*v)
	}
	return _u
}

// SetTemplateID sets the "template_id" field.
func (_u *ProcessUpdateOne) SetTemplateID(v string) *ProcessUpdateOne {
	_u.mutation.SetTemplateID(v)
	return _u
}

// SetNillableTemplateID sets the "template_id" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableTemplateID(v *string) *ProcessUpdateOne {
	if v != nil {
		_u.SetTemplateID(*v)
	}
	return _u
}

// SetBusinessKey sets the "business_key" field.
func (_u *ProcessUpdateOne) SetBusinessKey(v string) *ProcessUpdateOne {
	_u.mutation.SetBusinessKey(v)
	return _u
}

// SetNillableBusinessKey sets the "business_key" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableBusinessKey(v *string) *ProcessUpdateOne {
	if v != nil {
		_u.SetBusinessKey(*v)
	}
	return _u
}

// SetFormCode sets the "form_code" field.
func (_u *ProcessUpdateOne) SetFormCode(v string) *ProcessUpdateOne {
	_u.mutation.SetFormCode(v)
	return _u
}

// SetNillableFormCode sets the "form_code" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableFormCode(v *string) *ProcessUpdateOne {
	if v != nil {
		_u.SetFormCode(*v)
	}
	return _u
}

// SetFormVersion sets the "form_version" field.
func (_u *ProcessUpdateOne) SetFormVersion(v string) *ProcessUpdateOne {
	_u.mutation.SetFormVersion(v)
	return _u
}

// SetNillableFormVersion sets the "form_version" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableFormVersion(v *string) *ProcessUpdateOne {
	if v != nil {
		_u.SetFormVersion(*v)
	}
	return _u
}

// ClearFormVersion clears the value of the "form_version" field.
func (_u *ProcessUpdateOne) ClearFormVersion() *ProcessUpdateOne {
	_u.mutation.ClearFormVersion()
	return _u
}

// SetFormConfig sets the "form_config" field.
func (_u *ProcessUpdateOne) SetFormConfig(v map[string]interface{}) *ProcessUpdateOne {
	_u.mutation.SetFormConfig(v)
	return _u
}

// ClearFormConfig clears the value of the "form_config" field.
func (_u *ProcessUpdateOne) ClearFormConfig() *ProcessUpdateOne {
	_u.mutation.ClearFormConfig()
	return _u
}

// SetFormPermissions sets the "form_permissions" field.
func (_u *ProcessUpdateOne) SetFormPermissions(v map[string]interface{}) *ProcessUpdateOne {
	_u.mutation.SetFormPermissions(v)
	return _u
}

// ClearFormPermissions clears the value of the "form_permissions" field.
func (_u *ProcessUpdateOne) ClearFormPermissions() *ProcessUpdateOne {
	_u.mutation.ClearFormPermissions()
	return _u
}

// SetFieldPermissions sets the "field_permissions" field.
func (_u *ProcessUpdateOne) SetFieldPermissions(v map[string]interface{}) *ProcessUpdateOne {
	_u.mutation.SetFieldPermissions(v)
	return _u
}

// ClearFieldPermissions clears the value of the "field_permissions" field.
func (_u *ProcessUpdateOne) ClearFieldPermissions() *ProcessUpdateOne {
	_u.mutation.ClearFieldPermissions()
	return _u
}

// SetBusinessTags sets the "business_tags" field.
func (_u *ProcessUpdateOne) SetBusinessTags(v []string) *ProcessUpdateOne {
	_u.mutation.SetBusinessTags(v)
	return _u
}

// AppendBusinessTags appends value to the "business_tags" field.
func (_u *ProcessUpdateOne) AppendBusinessTags(v []string) *ProcessUpdateOne {
	_u.mutation.AppendBusinessTags(v)
	return _u
}

// ClearBusinessTags clears the value of the "business_tags" field.
func (_u *ProcessUpdateOne) ClearBusinessTags() *ProcessUpdateOne {
	_u.mutation.ClearBusinessTags()
	return _u
}

// SetModuleCode sets the "module_code" field.
func (_u *ProcessUpdateOne) SetModuleCode(v string) *ProcessUpdateOne {
	_u.mutation.SetModuleCode(v)
	return _u
}

// SetNillableModuleCode sets the "module_code" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableModuleCode(v *string) *ProcessUpdateOne {
	if v != nil {
		_u.SetModuleCode(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *ProcessUpdateOne) SetCategory(v string) *ProcessUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableCategory(v *string) *ProcessUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// ClearCategory clears the value of the "category" field.
func (_u *ProcessUpdateOne) ClearCategory() *ProcessUpdateOne {
	_u.mutation.ClearCategory()
	return _u
}

// SetFlowStatus sets the "flow_status" field.
func (_u *ProcessUpdateOne) SetFlowStatus(v string) *ProcessUpdateOne {
	_u.mutation.SetFlowStatus(v)
	return _u
}

// SetNillableFlowStatus sets the "flow_status" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableFlowStatus(v *string) *ProcessUpdateOne {
	if v != nil {
		_u.SetFlowStatus(*v)
	}
	return _u
}

// ClearFlowStatus clears the value of the "flow_status" field.
func (_u *ProcessUpdateOne) ClearFlowStatus() *ProcessUpdateOne {
	_u.mutation.ClearFlowStatus()
	return _u
}

// SetFlowVariables sets the "flow_variables" field.
func (_u *ProcessUpdateOne) SetFlowVariables(v map[string]interface{}) *ProcessUpdateOne {
	_u.mutation.SetFlowVariables(v)
	return _u
}

// ClearFlowVariables clears the value of the "flow_variables" field.
func (_u *ProcessUpdateOne) ClearFlowVariables() *ProcessUpdateOne {
	_u.mutation.ClearFlowVariables()
	return _u
}

// SetIsDraft sets the "is_draft" field.
func (_u *ProcessUpdateOne) SetIsDraft(v bool) *ProcessUpdateOne {
	_u.mutation.SetIsDraft(v)
	return _u
}

// SetNillableIsDraft sets the "is_draft" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableIsDraft(v *bool) *ProcessUpdateOne {
	if v != nil {
		_u.SetIsDraft(*v)
	}
	return _u
}

// SetIsTerminated sets the "is_terminated" field.
func (_u *ProcessUpdateOne) SetIsTerminated(v bool) *ProcessUpdateOne {
	_u.mutation.SetIsTerminated(v)
	return _u
}

// SetNillableIsTerminated sets the "is_terminated" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableIsTerminated(v *bool) *ProcessUpdateOne {
	if v != nil {
		_u.SetIsTerminated(*v)
	}
	return _u
}

// SetIsSuspended sets the "is_suspended" field.
func (_u *ProcessUpdateOne) SetIsSuspended(v bool) *ProcessUpdateOne {
	_u.mutation.SetIsSuspended(v)
	return _u
}

// SetNillableIsSuspended sets the "is_suspended" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableIsSuspended(v *bool) *ProcessUpdateOne {
	if v != nil {
		_u.SetIsSuspended(*v)
	}
	return _u
}

// SetSuspendReason sets the "suspend_reason" field.
func (_u *ProcessUpdateOne) SetSuspendReason(v string) *ProcessUpdateOne {
	_u.mutation.SetSuspendReason(v)
	return _u
}

// SetNillableSuspendReason sets the "suspend_reason" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableSuspendReason(v *string) *ProcessUpdateOne {
	if v != nil {
		_u.SetSuspendReason(*v)
	}
	return _u
}

// ClearSuspendReason clears the value of the "suspend_reason" field.
func (_u *ProcessUpdateOne) ClearSuspendReason() *ProcessUpdateOne {
	_u.mutation.ClearSuspendReason()
	return _u
}

// SetStartTime sets the "start_time" field.
func (_u *ProcessUpdateOne) SetStartTime(v int64) *ProcessUpdateOne {
	_u.mutation.ResetStartTime()
	_u.mutation.SetStartTime(v)
	return _u
}

// SetNillableStartTime sets the "start_time" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableStartTime(v *int64) *ProcessUpdateOne {
	if v != nil {
		_u.SetStartTime(*v)
	}
	return _u
}

// AddStartTime adds value to the "start_time" field.
func (_u *ProcessUpdateOne) AddStartTime(v int64) *ProcessUpdateOne {
	_u.mutation.AddStartTime(v)
	return _u
}

// SetEndTime sets the "end_time" field.
func (_u *ProcessUpdateOne) SetEndTime(v int64) *ProcessUpdateOne {
	_u.mutation.ResetEndTime()
	_u.mutation.SetEndTime(v)
	return _u
}

// SetNillableEndTime sets the "end_time" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableEndTime(v *int64) *ProcessUpdateOne {
	if v != nil {
		_u.SetEndTime(*v)
	}
	return _u
}

// AddEndTime adds value to the "end_time" field.
func (_u *ProcessUpdateOne) AddEndTime(v int64) *ProcessUpdateOne {
	_u.mutation.AddEndTime(v)
	return _u
}

// ClearEndTime clears the value of the "end_time" field.
func (_u *ProcessUpdateOne) ClearEndTime() *ProcessUpdateOne {
	_u.mutation.ClearEndTime()
	return _u
}

// SetDueTime sets the "due_time" field.
func (_u *ProcessUpdateOne) SetDueTime(v int64) *ProcessUpdateOne {
	_u.mutation.ResetDueTime()
	_u.mutation.SetDueTime(v)
	return _u
}

// SetNillableDueTime sets the "due_time" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableDueTime(v *int64) *ProcessUpdateOne {
	if v != nil {
		_u.SetDueTime(*v)
	}
	return _u
}

// AddDueTime adds value to the "due_time" field.
func (_u *ProcessUpdateOne) AddDueTime(v int64) *ProcessUpdateOne {
	_u.mutation.AddDueTime(v)
	return _u
}

// ClearDueTime clears the value of the "due_time" field.
func (_u *ProcessUpdateOne) ClearDueTime() *ProcessUpdateOne {
	_u.mutation.ClearDueTime()
	return _u
}

// SetDuration sets the "duration" field.
func (_u *ProcessUpdateOne) SetDuration(v int) *ProcessUpdateOne {
	_u.mutation.ResetDuration()
	_u.mutation.SetDuration(v)
	return _u
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableDuration(v *int) *ProcessUpdateOne {
	if v != nil {
		_u.SetDuration(*v)
	}
	return _u
}

// AddDuration adds value to the "duration" field.
func (_u *ProcessUpdateOne) AddDuration(v int) *ProcessUpdateOne {
	_u.mutation.AddDuration(v)
	return _u
}

// ClearDuration clears the value of the "duration" field.
func (_u *ProcessUpdateOne) ClearDuration() *ProcessUpdateOne {
	_u.mutation.ClearDuration()
	return _u
}

// SetPriority sets the "priority" field.
func (_u *ProcessUpdateOne) SetPriority(v int) *ProcessUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillablePriority(v *int) *ProcessUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *ProcessUpdateOne) AddPriority(v int) *ProcessUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetIsTimeout sets the "is_timeout" field.
func (_u *ProcessUpdateOne) SetIsTimeout(v bool) *ProcessUpdateOne {
	_u.mutation.SetIsTimeout(v)
	return _u
}

// SetNillableIsTimeout sets the "is_timeout" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableIsTimeout(v *bool) *ProcessUpdateOne {
	if v != nil {
		_u.SetIsTimeout(*v)
	}
	return _u
}

// SetReminderCount sets the "reminder_count" field.
func (_u *ProcessUpdateOne) SetReminderCount(v int) *ProcessUpdateOne {
	_u.mutation.ResetReminderCount()
	_u.mutation.SetReminderCount(v)
	return _u
}

// SetNillableReminderCount sets the "reminder_count" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableReminderCount(v *int) *ProcessUpdateOne {
	if v != nil {
		_u.SetReminderCount(*v)
	}
	return _u
}

// AddReminderCount adds value to the "reminder_count" field.
func (_u *ProcessUpdateOne) AddReminderCount(v int) *ProcessUpdateOne {
	_u.mutation.AddReminderCount(v)
	return _u
}

// SetAllowCancel sets the "allow_cancel" field.
func (_u *ProcessUpdateOne) SetAllowCancel(v bool) *ProcessUpdateOne {
	_u.mutation.SetAllowCancel(v)
	return _u
}

// SetNillableAllowCancel sets the "allow_cancel" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableAllowCancel(v *bool) *ProcessUpdateOne {
	if v != nil {
		_u.SetAllowCancel(*v)
	}
	return _u
}

// SetAllowUrge sets the "allow_urge" field.
func (_u *ProcessUpdateOne) SetAllowUrge(v bool) *ProcessUpdateOne {
	_u.mutation.SetAllowUrge(v)
	return _u
}

// SetNillableAllowUrge sets the "allow_urge" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableAllowUrge(v *bool) *ProcessUpdateOne {
	if v != nil {
		_u.SetAllowUrge(*v)
	}
	return _u
}

// SetAllowDelegate sets the "allow_delegate" field.
func (_u *ProcessUpdateOne) SetAllowDelegate(v bool) *ProcessUpdateOne {
	_u.mutation.SetAllowDelegate(v)
	return _u
}

// SetNillableAllowDelegate sets the "allow_delegate" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableAllowDelegate(v *bool) *ProcessUpdateOne {
	if v != nil {
		_u.SetAllowDelegate(*v)
	}
	return _u
}

// SetAllowTransfer sets the "allow_transfer" field.
func (_u *ProcessUpdateOne) SetAllowTransfer(v bool) *ProcessUpdateOne {
	_u.mutation.SetAllowTransfer(v)
	return _u
}

// SetNillableAllowTransfer sets the "allow_transfer" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableAllowTransfer(v *bool) *ProcessUpdateOne {
	if v != nil {
		_u.SetAllowTransfer(*v)
	}
	return _u
}

// SetIsDraftEnabled sets the "is_draft_enabled" field.
func (_u *ProcessUpdateOne) SetIsDraftEnabled(v bool) *ProcessUpdateOne {
	_u.mutation.SetIsDraftEnabled(v)
	return _u
}

// SetNillableIsDraftEnabled sets the "is_draft_enabled" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableIsDraftEnabled(v *bool) *ProcessUpdateOne {
	if v != nil {
		_u.SetIsDraftEnabled(*v)
	}
	return _u
}

// SetIsAutoStart sets the "is_auto_start" field.
func (_u *ProcessUpdateOne) SetIsAutoStart(v bool) *ProcessUpdateOne {
	_u.mutation.SetIsAutoStart(v)
	return _u
}

// SetNillableIsAutoStart sets the "is_auto_start" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableIsAutoStart(v *bool) *ProcessUpdateOne {
	if v != nil {
		_u.SetIsAutoStart(*v)
	}
	return _u
}

// SetStrictMode sets the "strict_mode" field.
func (_u *ProcessUpdateOne) SetStrictMode(v bool) *ProcessUpdateOne {
	_u.mutation.SetStrictMode(v)
	return _u
}

// SetNillableStrictMode sets the "strict_mode" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableStrictMode(v *bool) *ProcessUpdateOne {
	if v != nil {
		_u.SetStrictMode(*v)
	}
	return _u
}

// SetExtras sets the "extras" field.
func (_u *ProcessUpdateOne) SetExtras(v map[string]interface{}) *ProcessUpdateOne {
	_u.mutation.SetExtras(v)
	return _u
}

// ClearExtras clears the value of the "extras" field.
func (_u *ProcessUpdateOne) ClearExtras() *ProcessUpdateOne {
	_u.mutation.ClearExtras()
	return _u
}

// SetSpaceID sets the "space_id" field.
func (_u *ProcessUpdateOne) SetSpaceID(v string) *ProcessUpdateOne {
	_u.mutation.SetSpaceID(v)
	return _u
}

// SetNillableSpaceID sets the "space_id" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableSpaceID(v *string) *ProcessUpdateOne {
	if v != nil {
		_u.SetSpaceID(*v)
	}
	return _u
}

// ClearSpaceID clears the value of the "space_id" field.
func (_u *ProcessUpdateOne) ClearSpaceID() *ProcessUpdateOne {
	_u.mutation.ClearSpaceID()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ProcessUpdateOne) SetCreatedBy(v string) *ProcessUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableCreatedBy(v *string) *ProcessUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ProcessUpdateOne) ClearCreatedBy() *ProcessUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *ProcessUpdateOne) SetUpdatedBy(v string) *ProcessUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableUpdatedBy(v *string) *ProcessUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *ProcessUpdateOne) ClearUpdatedBy() *ProcessUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProcessUpdateOne) SetUpdatedAt(v int64) *ProcessUpdateOne {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *ProcessUpdateOne) AddUpdatedAt(v int64) *ProcessUpdateOne {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *ProcessUpdateOne) ClearUpdatedAt() *ProcessUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetProcessKey sets the "process_key" field.
func (_u *ProcessUpdateOne) SetProcessKey(v string) *ProcessUpdateOne {
	_u.mutation.SetProcessKey(v)
	return _u
}

// SetNillableProcessKey sets the "process_key" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableProcessKey(v *string) *ProcessUpdateOne {
	if v != nil {
		_u.SetProcessKey(*v)
	}
	return _u
}

// SetInitiator sets the "initiator" field.
func (_u *ProcessUpdateOne) SetInitiator(v string) *ProcessUpdateOne {
	_u.mutation.SetInitiator(v)
	return _u
}

// SetNillableInitiator sets the "initiator" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableInitiator(v *string) *ProcessUpdateOne {
	if v != nil {
		_u.SetInitiator(*v)
	}
	return _u
}

// SetInitiatorDept sets the "initiator_dept" field.
func (_u *ProcessUpdateOne) SetInitiatorDept(v string) *ProcessUpdateOne {
	_u.mutation.SetInitiatorDept(v)
	return _u
}

// SetNillableInitiatorDept sets the "initiator_dept" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableInitiatorDept(v *string) *ProcessUpdateOne {
	if v != nil {
		_u.SetInitiatorDept(*v)
	}
	return _u
}

// ClearInitiatorDept clears the value of the "initiator_dept" field.
func (_u *ProcessUpdateOne) ClearInitiatorDept() *ProcessUpdateOne {
	_u.mutation.ClearInitiatorDept()
	return _u
}

// SetProcessCode sets the "process_code" field.
func (_u *ProcessUpdateOne) SetProcessCode(v string) *ProcessUpdateOne {
	_u.mutation.SetProcessCode(v)
	return _u
}

// SetNillableProcessCode sets the "process_code" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableProcessCode(v *string) *ProcessUpdateOne {
	if v != nil {
		_u.SetProcessCode(*v)
	}
	return _u
}

// SetVariables sets the "variables" field.
func (_u *ProcessUpdateOne) SetVariables(v map[string]interface{}) *ProcessUpdateOne {
	_u.mutation.SetVariables(v)
	return _u
}

// SetCurrentNode sets the "current_node" field.
func (_u *ProcessUpdateOne) SetCurrentNode(v string) *ProcessUpdateOne {
	_u.mutation.SetCurrentNode(v)
	return _u
}

// SetNillableCurrentNode sets the "current_node" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableCurrentNode(v *string) *ProcessUpdateOne {
	if v != nil {
		_u.SetCurrentNode(*v)
	}
	return _u
}

// ClearCurrentNode clears the value of the "current_node" field.
func (_u *ProcessUpdateOne) ClearCurrentNode() *ProcessUpdateOne {
	_u.mutation.ClearCurrentNode()
	return _u
}

// SetActiveNodes sets the "active_nodes" field.
func (_u *ProcessUpdateOne) SetActiveNodes(v []string) *ProcessUpdateOne {
	_u.mutation.SetActiveNodes(v)
	return _u
}

// AppendActiveNodes appends value to the "active_nodes" field.
func (_u *ProcessUpdateOne) AppendActiveNodes(v []string) *ProcessUpdateOne {
	_u.mutation.AppendActiveNodes(v)
	return _u
}

// ClearActiveNodes clears the value of the "active_nodes" field.
func (_u *ProcessUpdateOne) ClearActiveNodes() *ProcessUpdateOne {
	_u.mutation.ClearActiveNodes()
	return _u
}

// SetProcessSnapshot sets the "process_snapshot" field.
func (_u *ProcessUpdateOne) SetProcessSnapshot(v map[string]interface{}) *ProcessUpdateOne {
	_u.mutation.SetProcessSnapshot(v)
	return _u
}

// ClearProcessSnapshot clears the value of the "process_snapshot" field.
func (_u *ProcessUpdateOne) ClearProcessSnapshot() *ProcessUpdateOne {
	_u.mutation.ClearProcessSnapshot()
	return _u
}

// SetFormSnapshot sets the "form_snapshot" field.
func (_u *ProcessUpdateOne) SetFormSnapshot(v map[string]interface{}) *ProcessUpdateOne {
	_u.mutation.SetFormSnapshot(v)
	return _u
}

// ClearFormSnapshot clears the value of the "form_snapshot" field.
func (_u *ProcessUpdateOne) ClearFormSnapshot() *ProcessUpdateOne {
	_u.mutation.ClearFormSnapshot()
	return _u
}

// SetUrgeCount sets the "urge_count" field.
func (_u *ProcessUpdateOne) SetUrgeCount(v int) *ProcessUpdateOne {
	_u.mutation.ResetUrgeCount()
	_u.mutation.SetUrgeCount(v)
	return _u
}

// SetNillableUrgeCount sets the "urge_count" field if the given value is not nil.
func (_u *ProcessUpdateOne) SetNillableUrgeCount(v *int) *ProcessUpdateOne {
	if v != nil {
		_u.SetUrgeCount(*v)
	}
	return _u
}

// AddUrgeCount adds value to the "urge_count" field.
func (_u *ProcessUpdateOne) AddUrgeCount(v int) *ProcessUpdateOne {
	_u.mutation.AddUrgeCount(v)
	return _u
}

// Mutation returns the ProcessMutation object of the builder.
func (_u *ProcessUpdateOne) Mutation() *ProcessMutation {
	return _u.mutation
}

// Where appends a list predicates to the ProcessUpdate builder.
func (_u *ProcessUpdateOne) Where(ps ...predicate.Process) *ProcessUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProcessUpdateOne) Select(field string, fields ...string) *ProcessUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Process entity.
func (_u *ProcessUpdateOne) Save(ctx context.Context) (*Process, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProcessUpdateOne) SaveX(ctx context.Context) *Process {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProcessUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProcessUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProcessUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := process.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ProcessUpdateOne) sqlSave(ctx context.Context) (_node *Process, err error) {
	_spec := sqlgraph.NewUpdateSpec(process.Table, process.Columns, sqlgraph.NewFieldSpec(process.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Process.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, process.FieldID)
		for _, f := range fields {
			if !process.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != process.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(process.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.StatusCleared() {
		_spec.ClearField(process.FieldStatus, field.TypeString)
	}
	if value, ok := _u.mutation.ProcessID(); ok {
		_spec.SetField(process.FieldProcessID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TemplateID(); ok {
		_spec.SetField(process.FieldTemplateID, field.TypeString, value)
	}
	if value, ok := _u.mutation.BusinessKey(); ok {
		_spec.SetField(process.FieldBusinessKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.FormCode(); ok {
		_spec.SetField(process.FieldFormCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.FormVersion(); ok {
		_spec.SetField(process.FieldFormVersion, field.TypeString, value)
	}
	if _u.mutation.FormVersionCleared() {
		_spec.ClearField(process.FieldFormVersion, field.TypeString)
	}
	if value, ok := _u.mutation.FormConfig(); ok {
		_spec.SetField(process.FieldFormConfig, field.TypeJSON, value)
	}
	if _u.mutation.FormConfigCleared() {
		_spec.ClearField(process.FieldFormConfig, field.TypeJSON)
	}
	if value, ok := _u.mutation.FormPermissions(); ok {
		_spec.SetField(process.FieldFormPermissions, field.TypeJSON, value)
	}
	if _u.mutation.FormPermissionsCleared() {
		_spec.ClearField(process.FieldFormPermissions, field.TypeJSON)
	}
	if value, ok := _u.mutation.FieldPermissions(); ok {
		_spec.SetField(process.FieldFieldPermissions, field.TypeJSON, value)
	}
	if _u.mutation.FieldPermissionsCleared() {
		_spec.ClearField(process.FieldFieldPermissions, field.TypeJSON)
	}
	if value, ok := _u.mutation.BusinessTags(); ok {
		_spec.SetField(process.FieldBusinessTags, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedBusinessTags(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, process.FieldBusinessTags, value)
		})
	}
	if _u.mutation.BusinessTagsCleared() {
		_spec.ClearField(process.FieldBusinessTags, field.TypeJSON)
	}
	if value, ok := _u.mutation.ModuleCode(); ok {
		_spec.SetField(process.FieldModuleCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(process.FieldCategory, field.TypeString, value)
	}
	if _u.mutation.CategoryCleared() {
		_spec.ClearField(process.FieldCategory, field.TypeString)
	}
	if value, ok := _u.mutation.FlowStatus(); ok {
		_spec.SetField(process.FieldFlowStatus, field.TypeString, value)
	}
	if _u.mutation.FlowStatusCleared() {
		_spec.ClearField(process.FieldFlowStatus, field.TypeString)
	}
	if value, ok := _u.mutation.FlowVariables(); ok {
		_spec.SetField(process.FieldFlowVariables, field.TypeJSON, value)
	}
	if _u.mutation.FlowVariablesCleared() {
		_spec.ClearField(process.FieldFlowVariables, field.TypeJSON)
	}
	if value, ok := _u.mutation.IsDraft(); ok {
		_spec.SetField(process.FieldIsDraft, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsTerminated(); ok {
		_spec.SetField(process.FieldIsTerminated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsSuspended(); ok {
		_spec.SetField(process.FieldIsSuspended, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SuspendReason(); ok {
		_spec.SetField(process.FieldSuspendReason, field.TypeString, value)
	}
	if _u.mutation.SuspendReasonCleared() {
		_spec.ClearField(process.FieldSuspendReason, field.TypeString)
	}
	if value, ok := _u.mutation.StartTime(); ok {
		_spec.SetField(process.FieldStartTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedStartTime(); ok {
		_spec.AddField(process.FieldStartTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.EndTime(); ok {
		_spec.SetField(process.FieldEndTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedEndTime(); ok {
		_spec.AddField(process.FieldEndTime, field.TypeInt64, value)
	}
	if _u.mutation.EndTimeCleared() {
		_spec.ClearField(process.FieldEndTime, field.TypeInt64)
	}
	if value, ok := _u.mutation.DueTime(); ok {
		_spec.SetField(process.FieldDueTime, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedDueTime(); ok {
		_spec.AddField(process.FieldDueTime, field.TypeInt64, value)
	}
	if _u.mutation.DueTimeCleared() {
		_spec.ClearField(process.FieldDueTime, field.TypeInt64)
	}
	if value, ok := _u.mutation.Duration(); ok {
		_spec.SetField(process.FieldDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDuration(); ok {
		_spec.AddField(process.FieldDuration, field.TypeInt, value)
	}
	if _u.mutation.DurationCleared() {
		_spec.ClearField(process.FieldDuration, field.TypeInt)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(process.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(process.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsTimeout(); ok {
		_spec.SetField(process.FieldIsTimeout, field.TypeBool, value)
	}
	if value, ok := _u.mutation.ReminderCount(); ok {
		_spec.SetField(process.FieldReminderCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedReminderCount(); ok {
		_spec.AddField(process.FieldReminderCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AllowCancel(); ok {
		_spec.SetField(process.FieldAllowCancel, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowUrge(); ok {
		_spec.SetField(process.FieldAllowUrge, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowDelegate(); ok {
		_spec.SetField(process.FieldAllowDelegate, field.TypeBool, value)
	}
	if value, ok := _u.mutation.AllowTransfer(); ok {
		_spec.SetField(process.FieldAllowTransfer, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsDraftEnabled(); ok {
		_spec.SetField(process.FieldIsDraftEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IsAutoStart(); ok {
		_spec.SetField(process.FieldIsAutoStart, field.TypeBool, value)
	}
	if value, ok := _u.mutation.StrictMode(); ok {
		_spec.SetField(process.FieldStrictMode, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Extras(); ok {
		_spec.SetField(process.FieldExtras, field.TypeJSON, value)
	}
	if _u.mutation.ExtrasCleared() {
		_spec.ClearField(process.FieldExtras, field.TypeJSON)
	}
	if value, ok := _u.mutation.SpaceID(); ok {
		_spec.SetField(process.FieldSpaceID, field.TypeString, value)
	}
	if _u.mutation.SpaceIDCleared() {
		_spec.ClearField(process.FieldSpaceID, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(process.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(process.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(process.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(process.FieldUpdatedBy, field.TypeString)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(process.FieldCreatedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(process.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(process.FieldUpdatedAt, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(process.FieldUpdatedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.ProcessKey(); ok {
		_spec.SetField(process.FieldProcessKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Initiator(); ok {
		_spec.SetField(process.FieldInitiator, field.TypeString, value)
	}
	if value, ok := _u.mutation.InitiatorDept(); ok {
		_spec.SetField(process.FieldInitiatorDept, field.TypeString, value)
	}
	if _u.mutation.InitiatorDeptCleared() {
		_spec.ClearField(process.FieldInitiatorDept, field.TypeString)
	}
	if value, ok := _u.mutation.ProcessCode(); ok {
		_spec.SetField(process.FieldProcessCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Variables(); ok {
		_spec.SetField(process.FieldVariables, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.CurrentNode(); ok {
		_spec.SetField(process.FieldCurrentNode, field.TypeString, value)
	}
	if _u.mutation.CurrentNodeCleared() {
		_spec.ClearField(process.FieldCurrentNode, field.TypeString)
	}
	if value, ok := _u.mutation.ActiveNodes(); ok {
		_spec.SetField(process.FieldActiveNodes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedActiveNodes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, process.FieldActiveNodes, value)
		})
	}
	if _u.mutation.ActiveNodesCleared() {
		_spec.ClearField(process.FieldActiveNodes, field.TypeJSON)
	}
	if value, ok := _u.mutation.ProcessSnapshot(); ok {
		_spec.SetField(process.FieldProcessSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.ProcessSnapshotCleared() {
		_spec.ClearField(process.FieldProcessSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.FormSnapshot(); ok {
		_spec.SetField(process.FieldFormSnapshot, field.TypeJSON, value)
	}
	if _u.mutation.FormSnapshotCleared() {
		_spec.ClearField(process.FieldFormSnapshot, field.TypeJSON)
	}
	if value, ok := _u.mutation.UrgeCount(); ok {
		_spec.SetField(process.FieldUrgeCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedUrgeCount(); ok {
		_spec.AddField(process.FieldUrgeCount, field.TypeInt, value)
	}
	_node = &Process{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{process.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
