// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ncobase/plugin/payment/data/ent/paymentchannel"
	"ncobase/plugin/payment/data/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
)

// PaymentChannelUpdate is the builder for updating PaymentChannel entities.
type PaymentChannelUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentChannelMutation
}

// Where appends a list predicates to the PaymentChannelUpdate builder.
func (_u *PaymentChannelUpdate) Where(ps ...predicate.PaymentChannel) *PaymentChannelUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *PaymentChannelUpdate) SetName(v string) *PaymentChannelUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PaymentChannelUpdate) SetNillableName(v *string) *PaymentChannelUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *PaymentChannelUpdate) ClearName() *PaymentChannelUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetDescription sets the "description" field.
func (_u *PaymentChannelUpdate) SetDescription(v string) *PaymentChannelUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PaymentChannelUpdate) SetNillableDescription(v *string) *PaymentChannelUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PaymentChannelUpdate) ClearDescription() *PaymentChannelUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetExtras sets the "extras" field.
func (_u *PaymentChannelUpdate) SetExtras(v map[string]interface{}) *PaymentChannelUpdate {
	_u.mutation.SetExtras(v)
	return _u
}

// ClearExtras clears the value of the "extras" field.
func (_u *PaymentChannelUpdate) ClearExtras() *PaymentChannelUpdate {
	_u.mutation.ClearExtras()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *PaymentChannelUpdate) SetCreatedBy(v string) *PaymentChannelUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *PaymentChannelUpdate) SetNillableCreatedBy(v *string) *PaymentChannelUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *PaymentChannelUpdate) ClearCreatedBy() *PaymentChannelUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *PaymentChannelUpdate) SetUpdatedBy(v string) *PaymentChannelUpdate {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *PaymentChannelUpdate) SetNillableUpdatedBy(v *string) *PaymentChannelUpdate {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *PaymentChannelUpdate) ClearUpdatedBy() *PaymentChannelUpdate {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentChannelUpdate) SetUpdatedAt(v int64) *PaymentChannelUpdate {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *PaymentChannelUpdate) AddUpdatedAt(v int64) *PaymentChannelUpdate {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *PaymentChannelUpdate) ClearUpdatedAt() *PaymentChannelUpdate {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *PaymentChannelUpdate) SetProvider(v string) *PaymentChannelUpdate {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *PaymentChannelUpdate) SetNillableProvider(v *string) *PaymentChannelUpdate {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentChannelUpdate) SetStatus(v string) *PaymentChannelUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentChannelUpdate) SetNillableStatus(v *string) *PaymentChannelUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *PaymentChannelUpdate) SetIsDefault(v bool) *PaymentChannelUpdate {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *PaymentChannelUpdate) SetNillableIsDefault(v *bool) *PaymentChannelUpdate {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetSupportedTypes sets the "supported_types" field.
func (_u *PaymentChannelUpdate) SetSupportedTypes(v []string) *PaymentChannelUpdate {
	_u.mutation.SetSupportedTypes(v)
	return _u
}

// AppendSupportedTypes appends value to the "supported_types" field.
func (_u *PaymentChannelUpdate) AppendSupportedTypes(v []string) *PaymentChannelUpdate {
	_u.mutation.AppendSupportedTypes(v)
	return _u
}

// SetConfig sets the "config" field.
func (_u *PaymentChannelUpdate) SetConfig(v map[string]interface{}) *PaymentChannelUpdate {
	_u.mutation.SetConfig(v)
	return _u
}

// SetSpaceID sets the "space_id" field.
func (_u *PaymentChannelUpdate) SetSpaceID(v string) *PaymentChannelUpdate {
	_u.mutation.SetSpaceID(v)
	return _u
}

// SetNillableSpaceID sets the "space_id" field if the given value is not nil.
func (_u *PaymentChannelUpdate) SetNillableSpaceID(v *string) *PaymentChannelUpdate {
	if v != nil {
		_u.SetSpaceID(*v)
	}
	return _u
}

// ClearSpaceID clears the value of the "space_id" field.
func (_u *PaymentChannelUpdate) ClearSpaceID() *PaymentChannelUpdate {
	_u.mutation.ClearSpaceID()
	return _u
}

// Mutation returns the PaymentChannelMutation object of the builder.
func (_u *PaymentChannelUpdate) Mutation() *PaymentChannelMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentChannelUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentChannelUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentChannelUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentChannelUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentChannelUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := paymentchannel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentChannelUpdate) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := paymentchannel.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "PaymentChannel.provider": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentChannelUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentchannel.Table, paymentchannel.Columns, sqlgraph.NewFieldSpec(paymentchannel.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(paymentchannel.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(paymentchannel.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(paymentchannel.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(paymentchannel.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Extras(); ok {
		_spec.SetField(paymentchannel.FieldExtras, field.TypeJSON, value)
	}
	if _u.mutation.ExtrasCleared() {
		_spec.ClearField(paymentchannel.FieldExtras, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(paymentchannel.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(paymentchannel.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(paymentchannel.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(paymentchannel.FieldUpdatedBy, field.TypeString)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(paymentchannel.FieldCreatedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentchannel.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(paymentchannel.FieldUpdatedAt, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(paymentchannel.FieldUpdatedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(paymentchannel.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentchannel.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(paymentchannel.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SupportedTypes(); ok {
		_spec.SetField(paymentchannel.FieldSupportedTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSupportedTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, paymentchannel.FieldSupportedTypes, value)
		})
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(paymentchannel.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.SpaceID(); ok {
		_spec.SetField(paymentchannel.FieldSpaceID, field.TypeString, value)
	}
	if _u.mutation.SpaceIDCleared() {
		_spec.ClearField(paymentchannel.FieldSpaceID, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentchannel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentChannelUpdateOne is the builder for updating a single PaymentChannel entity.
type PaymentChannelUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentChannelMutation
}

// SetName sets the "name" field.
func (_u *PaymentChannelUpdateOne) SetName(v string) *PaymentChannelUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *PaymentChannelUpdateOne) SetNillableName(v *string) *PaymentChannelUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *PaymentChannelUpdateOne) ClearName() *PaymentChannelUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetDescription sets the "description" field.
func (_u *PaymentChannelUpdateOne) SetDescription(v string) *PaymentChannelUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *PaymentChannelUpdateOne) SetNillableDescription(v *string) *PaymentChannelUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *PaymentChannelUpdateOne) ClearDescription() *PaymentChannelUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetExtras sets the "extras" field.
func (_u *PaymentChannelUpdateOne) SetExtras(v map[string]interface{}) *PaymentChannelUpdateOne {
	_u.mutation.SetExtras(v)
	return _u
}

// ClearExtras clears the value of the "extras" field.
func (_u *PaymentChannelUpdateOne) ClearExtras() *PaymentChannelUpdateOne {
	_u.mutation.ClearExtras()
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *PaymentChannelUpdateOne) SetCreatedBy(v string) *PaymentChannelUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *PaymentChannelUpdateOne) SetNillableCreatedBy(v *string) *PaymentChannelUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *PaymentChannelUpdateOne) ClearCreatedBy() *PaymentChannelUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// SetUpdatedBy sets the "updated_by" field.
func (_u *PaymentChannelUpdateOne) SetUpdatedBy(v string) *PaymentChannelUpdateOne {
	_u.mutation.SetUpdatedBy(v)
	return _u
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_u *PaymentChannelUpdateOne) SetNillableUpdatedBy(v *string) *PaymentChannelUpdateOne {
	if v != nil {
		_u.SetUpdatedBy(*v)
	}
	return _u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (_u *PaymentChannelUpdateOne) ClearUpdatedBy() *PaymentChannelUpdateOne {
	_u.mutation.ClearUpdatedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PaymentChannelUpdateOne) SetUpdatedAt(v int64) *PaymentChannelUpdateOne {
	_u.mutation.ResetUpdatedAt()
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddUpdatedAt adds value to the "updated_at" field.
func (_u *PaymentChannelUpdateOne) AddUpdatedAt(v int64) *PaymentChannelUpdateOne {
	_u.mutation.AddUpdatedAt(v)
	return _u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (_u *PaymentChannelUpdateOne) ClearUpdatedAt() *PaymentChannelUpdateOne {
	_u.mutation.ClearUpdatedAt()
	return _u
}

// SetProvider sets the "provider" field.
func (_u *PaymentChannelUpdateOne) SetProvider(v string) *PaymentChannelUpdateOne {
	_u.mutation.SetProvider(v)
	return _u
}

// SetNillableProvider sets the "provider" field if the given value is not nil.
func (_u *PaymentChannelUpdateOne) SetNillableProvider(v *string) *PaymentChannelUpdateOne {
	if v != nil {
		_u.SetProvider(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentChannelUpdateOne) SetStatus(v string) *PaymentChannelUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentChannelUpdateOne) SetNillableStatus(v *string) *PaymentChannelUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsDefault sets the "is_default" field.
func (_u *PaymentChannelUpdateOne) SetIsDefault(v bool) *PaymentChannelUpdateOne {
	_u.mutation.SetIsDefault(v)
	return _u
}

// SetNillableIsDefault sets the "is_default" field if the given value is not nil.
func (_u *PaymentChannelUpdateOne) SetNillableIsDefault(v *bool) *PaymentChannelUpdateOne {
	if v != nil {
		_u.SetIsDefault(*v)
	}
	return _u
}

// SetSupportedTypes sets the "supported_types" field.
func (_u *PaymentChannelUpdateOne) SetSupportedTypes(v []string) *PaymentChannelUpdateOne {
	_u.mutation.SetSupportedTypes(v)
	return _u
}

// AppendSupportedTypes appends value to the "supported_types" field.
func (_u *PaymentChannelUpdateOne) AppendSupportedTypes(v []string) *PaymentChannelUpdateOne {
	_u.mutation.AppendSupportedTypes(v)
	return _u
}

// SetConfig sets the "config" field.
func (_u *PaymentChannelUpdateOne) SetConfig(v map[string]interface{}) *PaymentChannelUpdateOne {
	_u.mutation.SetConfig(v)
	return _u
}

// SetSpaceID sets the "space_id" field.
func (_u *PaymentChannelUpdateOne) SetSpaceID(v string) *PaymentChannelUpdateOne {
	_u.mutation.SetSpaceID(v)
	return _u
}

// SetNillableSpaceID sets the "space_id" field if the given value is not nil.
func (_u *PaymentChannelUpdateOne) SetNillableSpaceID(v *string) *PaymentChannelUpdateOne {
	if v != nil {
		_u.SetSpaceID(*v)
	}
	return _u
}

// ClearSpaceID clears the value of the "space_id" field.
func (_u *PaymentChannelUpdateOne) ClearSpaceID() *PaymentChannelUpdateOne {
	_u.mutation.ClearSpaceID()
	return _u
}

// Mutation returns the PaymentChannelMutation object of the builder.
func (_u *PaymentChannelUpdateOne) Mutation() *PaymentChannelMutation {
	return _u.mutation
}

// Where appends a list predicates to the PaymentChannelUpdate builder.
func (_u *PaymentChannelUpdateOne) Where(ps ...predicate.PaymentChannel) *PaymentChannelUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentChannelUpdateOne) Select(field string, fields ...string) *PaymentChannelUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentChannel entity.
func (_u *PaymentChannelUpdateOne) Save(ctx context.Context) (*PaymentChannel, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentChannelUpdateOne) SaveX(ctx context.Context) *PaymentChannel {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentChannelUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentChannelUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PaymentChannelUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok && !_u.mutation.UpdatedAtCleared() {
		v := paymentchannel.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentChannelUpdateOne) check() error {
	if v, ok := _u.mutation.Provider(); ok {
		if err := paymentchannel.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "PaymentChannel.provider": %w`, err)}
		}
	}
	return nil
}

func (_u *PaymentChannelUpdateOne) sqlSave(ctx context.Context) (_node *PaymentChannel, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentchannel.Table, paymentchannel.Columns, sqlgraph.NewFieldSpec(paymentchannel.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentChannel.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentchannel.FieldID)
		for _, f := range fields {
			if !paymentchannel.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentchannel.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(paymentchannel.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(paymentchannel.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(paymentchannel.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(paymentchannel.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Extras(); ok {
		_spec.SetField(paymentchannel.FieldExtras, field.TypeJSON, value)
	}
	if _u.mutation.ExtrasCleared() {
		_spec.ClearField(paymentchannel.FieldExtras, field.TypeJSON)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(paymentchannel.FieldCreatedBy, field.TypeString, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(paymentchannel.FieldCreatedBy, field.TypeString)
	}
	if value, ok := _u.mutation.UpdatedBy(); ok {
		_spec.SetField(paymentchannel.FieldUpdatedBy, field.TypeString, value)
	}
	if _u.mutation.UpdatedByCleared() {
		_spec.ClearField(paymentchannel.FieldUpdatedBy, field.TypeString)
	}
	if _u.mutation.CreatedAtCleared() {
		_spec.ClearField(paymentchannel.FieldCreatedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(paymentchannel.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(paymentchannel.FieldUpdatedAt, field.TypeInt64, value)
	}
	if _u.mutation.UpdatedAtCleared() {
		_spec.ClearField(paymentchannel.FieldUpdatedAt, field.TypeInt64)
	}
	if value, ok := _u.mutation.Provider(); ok {
		_spec.SetField(paymentchannel.FieldProvider, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentchannel.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.IsDefault(); ok {
		_spec.SetField(paymentchannel.FieldIsDefault, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SupportedTypes(); ok {
		_spec.SetField(paymentchannel.FieldSupportedTypes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSupportedTypes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, paymentchannel.FieldSupportedTypes, value)
		})
	}
	if value, ok := _u.mutation.Config(); ok {
		_spec.SetField(paymentchannel.FieldConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.SpaceID(); ok {
		_spec.SetField(paymentchannel.FieldSpaceID, field.TypeString, value)
	}
	if _u.mutation.SpaceIDCleared() {
		_spec.ClearField(paymentchannel.FieldSpaceID, field.TypeString)
	}
	_node = &PaymentChannel{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentchannel.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
