// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"ncobase/core/space/data/ent/spacequota"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SpaceQuotaCreate is the builder for creating a SpaceQuota entity.
type SpaceQuotaCreate struct {
	config
	mutation *SpaceQuotaMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetSpaceID sets the "space_id" field.
func (_c *SpaceQuotaCreate) SetSpaceID(v string) *SpaceQuotaCreate {
	_c.mutation.SetSpaceID(v)
	return _c
}

// SetNillableSpaceID sets the "space_id" field if the given value is not nil.
func (_c *SpaceQuotaCreate) SetNillableSpaceID(v *string) *SpaceQuotaCreate {
	if v != nil {
		_c.SetSpaceID(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *SpaceQuotaCreate) SetDescription(v string) *SpaceQuotaCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SpaceQuotaCreate) SetNillableDescription(v *string) *SpaceQuotaCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetExtras sets the "extras" field.
func (_c *SpaceQuotaCreate) SetExtras(v map[string]interface{}) *SpaceQuotaCreate {
	_c.mutation.SetExtras(v)
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *SpaceQuotaCreate) SetCreatedBy(v string) *SpaceQuotaCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_c *SpaceQuotaCreate) SetNillableCreatedBy(v *string) *SpaceQuotaCreate {
	if v != nil {
		_c.SetCreatedBy(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *SpaceQuotaCreate) SetUpdatedBy(v string) *SpaceQuotaCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *SpaceQuotaCreate) SetNillableUpdatedBy(v *string) *SpaceQuotaCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SpaceQuotaCreate) SetCreatedAt(v int64) *SpaceQuotaCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SpaceQuotaCreate) SetNillableCreatedAt(v *int64) *SpaceQuotaCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SpaceQuotaCreate) SetUpdatedAt(v int64) *SpaceQuotaCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SpaceQuotaCreate) SetNillableUpdatedAt(v *int64) *SpaceQuotaCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetQuotaType sets the "quota_type" field.
func (_c *SpaceQuotaCreate) SetQuotaType(v string) *SpaceQuotaCreate {
	_c.mutation.SetQuotaType(v)
	return _c
}

// SetQuotaName sets the "quota_name" field.
func (_c *SpaceQuotaCreate) SetQuotaName(v string) *SpaceQuotaCreate {
	_c.mutation.SetQuotaName(v)
	return _c
}

// SetMaxValue sets the "max_value" field.
func (_c *SpaceQuotaCreate) SetMaxValue(v int64) *SpaceQuotaCreate {
	_c.mutation.SetMaxValue(v)
	return _c
}

// SetCurrentUsed sets the "current_used" field.
func (_c *SpaceQuotaCreate) SetCurrentUsed(v int64) *SpaceQuotaCreate {
	_c.mutation.SetCurrentUsed(v)
	return _c
}

// SetNillableCurrentUsed sets the "current_used" field if the given value is not nil.
func (_c *SpaceQuotaCreate) SetNillableCurrentUsed(v *int64) *SpaceQuotaCreate {
	if v != nil {
		_c.SetCurrentUsed(*v)
	}
	return _c
}

// SetUnit sets the "unit" field.
func (_c *SpaceQuotaCreate) SetUnit(v string) *SpaceQuotaCreate {
	_c.mutation.SetUnit(v)
	return _c
}

// SetNillableUnit sets the "unit" field if the given value is not nil.
func (_c *SpaceQuotaCreate) SetNillableUnit(v *string) *SpaceQuotaCreate {
	if v != nil {
		_c.SetUnit(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *SpaceQuotaCreate) SetEnabled(v bool) *SpaceQuotaCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *SpaceQuotaCreate) SetNillableEnabled(v *bool) *SpaceQuotaCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SpaceQuotaCreate) SetID(v string) *SpaceQuotaCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SpaceQuotaCreate) SetNillableID(v *string) *SpaceQuotaCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the SpaceQuotaMutation object of the builder.
func (_c *SpaceQuotaCreate) Mutation() *SpaceQuotaMutation {
	return _c.mutation
}

// Save creates the SpaceQuota in the database.
func (_c *SpaceQuotaCreate) Save(ctx context.Context) (*SpaceQuota, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SpaceQuotaCreate) SaveX(ctx context.Context) *SpaceQuota {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SpaceQuotaCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SpaceQuotaCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SpaceQuotaCreate) defaults() {
	if _, ok := _c.mutation.Extras(); !ok {
		v := spacequota.DefaultExtras
		_c.mutation.SetExtras(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := spacequota.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := spacequota.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.CurrentUsed(); !ok {
		v := spacequota.DefaultCurrentUsed
		_c.mutation.SetCurrentUsed(v)
	}
	if _, ok := _c.mutation.Unit(); !ok {
		v := spacequota.DefaultUnit
		_c.mutation.SetUnit(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := spacequota.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := spacequota.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SpaceQuotaCreate) check() error {
	if _, ok := _c.mutation.QuotaType(); !ok {
		return &ValidationError{Name: "quota_type", err: errors.New(`ent: missing required field "SpaceQuota.quota_type"`)}
	}
	if v, ok := _c.mutation.QuotaType(); ok {
		if err := spacequota.QuotaTypeValidator(v); err != nil {
			return &ValidationError{Name: "quota_type", err: fmt.Errorf(`ent: validator failed for field "SpaceQuota.quota_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.QuotaName(); !ok {
		return &ValidationError{Name: "quota_name", err: errors.New(`ent: missing required field "SpaceQuota.quota_name"`)}
	}
	if v, ok := _c.mutation.QuotaName(); ok {
		if err := spacequota.QuotaNameValidator(v); err != nil {
			return &ValidationError{Name: "quota_name", err: fmt.Errorf(`ent: validator failed for field "SpaceQuota.quota_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.MaxValue(); !ok {
		return &ValidationError{Name: "max_value", err: errors.New(`ent: missing required field "SpaceQuota.max_value"`)}
	}
	if v, ok := _c.mutation.MaxValue(); ok {
		if err := spacequota.MaxValueValidator(v); err != nil {
			return &ValidationError{Name: "max_value", err: fmt.Errorf(`ent: validator failed for field "SpaceQuota.max_value": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CurrentUsed(); !ok {
		return &ValidationError{Name: "current_used", err: errors.New(`ent: missing required field "SpaceQuota.current_used"`)}
	}
	if v, ok := _c.mutation.CurrentUsed(); ok {
		if err := spacequota.CurrentUsedValidator(v); err != nil {
			return &ValidationError{Name: "current_used", err: fmt.Errorf(`ent: validator failed for field "SpaceQuota.current_used": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Unit(); !ok {
		return &ValidationError{Name: "unit", err: errors.New(`ent: missing required field "SpaceQuota.unit"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "SpaceQuota.enabled"`)}
	}
	if v, ok := _c.mutation.ID(); ok {
		if err := spacequota.IDValidator(v); err != nil {
			return &ValidationError{Name: "id", err: fmt.Errorf(`ent: validator failed for field "SpaceQuota.id": %w`, err)}
		}
	}
	return nil
}

func (_c *SpaceQuotaCreate) sqlSave(ctx context.Context) (*SpaceQuota, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected SpaceQuota.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SpaceQuotaCreate) createSpec() (*SpaceQuota, *sqlgraph.CreateSpec) {
	var (
		_node = &SpaceQuota{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(spacequota.Table, sqlgraph.NewFieldSpec(spacequota.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.SpaceID(); ok {
		_spec.SetField(spacequota.FieldSpaceID, field.TypeString, value)
		_node.SpaceID = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(spacequota.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.Extras(); ok {
		_spec.SetField(spacequota.FieldExtras, field.TypeJSON, value)
		_node.Extras = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(spacequota.FieldCreatedBy, field.TypeString, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(spacequota.FieldUpdatedBy, field.TypeString, value)
		_node.UpdatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(spacequota.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(spacequota.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.QuotaType(); ok {
		_spec.SetField(spacequota.FieldQuotaType, field.TypeString, value)
		_node.QuotaType = value
	}
	if value, ok := _c.mutation.QuotaName(); ok {
		_spec.SetField(spacequota.FieldQuotaName, field.TypeString, value)
		_node.QuotaName = value
	}
	if value, ok := _c.mutation.MaxValue(); ok {
		_spec.SetField(spacequota.FieldMaxValue, field.TypeInt64, value)
		_node.MaxValue = value
	}
	if value, ok := _c.mutation.CurrentUsed(); ok {
		_spec.SetField(spacequota.FieldCurrentUsed, field.TypeInt64, value)
		_node.CurrentUsed = value
	}
	if value, ok := _c.mutation.Unit(); ok {
		_spec.SetField(spacequota.FieldUnit, field.TypeString, value)
		_node.Unit = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(spacequota.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SpaceQuota.Create().
//		SetSpaceID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SpaceQuotaUpsert) {
//			SetSpaceID(v+v).
//		}).
//		Exec(ctx)
func (_c *SpaceQuotaCreate) OnConflict(opts ...sql.ConflictOption) *SpaceQuotaUpsertOne {
	_c.conflict = opts
	return &SpaceQuotaUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SpaceQuota.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SpaceQuotaCreate) OnConflictColumns(columns ...string) *SpaceQuotaUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SpaceQuotaUpsertOne{
		create: _c,
	}
}

type (
	// SpaceQuotaUpsertOne is the builder for "upsert"-ing
	//  one SpaceQuota node.
	SpaceQuotaUpsertOne struct {
		create *SpaceQuotaCreate
	}

	// SpaceQuotaUpsert is the "OnConflict" setter.
	SpaceQuotaUpsert struct {
		*sql.UpdateSet
	}
)

// SetSpaceID sets the "space_id" field.
func (u *SpaceQuotaUpsert) SetSpaceID(v string) *SpaceQuotaUpsert {
	u.Set(spacequota.FieldSpaceID, v)
	return u
}

// UpdateSpaceID sets the "space_id" field to the value that was provided on create.
func (u *SpaceQuotaUpsert) UpdateSpaceID() *SpaceQuotaUpsert {
	u.SetExcluded(spacequota.FieldSpaceID)
	return u
}

// ClearSpaceID clears the value of the "space_id" field.
func (u *SpaceQuotaUpsert) ClearSpaceID() *SpaceQuotaUpsert {
	u.SetNull(spacequota.FieldSpaceID)
	return u
}

// SetDescription sets the "description" field.
func (u *SpaceQuotaUpsert) SetDescription(v string) *SpaceQuotaUpsert {
	u.Set(spacequota.FieldDescription, v)
	return u
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SpaceQuotaUpsert) UpdateDescription() *SpaceQuotaUpsert {
	u.SetExcluded(spacequota.FieldDescription)
	return u
}

// ClearDescription clears the value of the "description" field.
func (u *SpaceQuotaUpsert) ClearDescription() *SpaceQuotaUpsert {
	u.SetNull(spacequota.FieldDescription)
	return u
}

// SetExtras sets the "extras" field.
func (u *SpaceQuotaUpsert) SetExtras(v map[string]interface{}) *SpaceQuotaUpsert {
	u.Set(spacequota.FieldExtras, v)
	return u
}

// UpdateExtras sets the "extras" field to the value that was provided on create.
func (u *SpaceQuotaUpsert) UpdateExtras() *SpaceQuotaUpsert {
	u.SetExcluded(spacequota.FieldExtras)
	return u
}

// ClearExtras clears the value of the "extras" field.
func (u *SpaceQuotaUpsert) ClearExtras() *SpaceQuotaUpsert {
	u.SetNull(spacequota.FieldExtras)
	return u
}

// SetCreatedBy sets the "created_by" field.
func (u *SpaceQuotaUpsert) SetCreatedBy(v string) *SpaceQuotaUpsert {
	u.Set(spacequota.FieldCreatedBy, v)
	return u
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SpaceQuotaUpsert) UpdateCreatedBy() *SpaceQuotaUpsert {
	u.SetExcluded(spacequota.FieldCreatedBy)
	return u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *SpaceQuotaUpsert) ClearCreatedBy() *SpaceQuotaUpsert {
	u.SetNull(spacequota.FieldCreatedBy)
	return u
}

// SetUpdatedBy sets the "updated_by" field.
func (u *SpaceQuotaUpsert) SetUpdatedBy(v string) *SpaceQuotaUpsert {
	u.Set(spacequota.FieldUpdatedBy, v)
	return u
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *SpaceQuotaUpsert) UpdateUpdatedBy() *SpaceQuotaUpsert {
	u.SetExcluded(spacequota.FieldUpdatedBy)
	return u
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *SpaceQuotaUpsert) ClearUpdatedBy() *SpaceQuotaUpsert {
	u.SetNull(spacequota.FieldUpdatedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SpaceQuotaUpsert) SetUpdatedAt(v int64) *SpaceQuotaUpsert {
	u.Set(spacequota.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SpaceQuotaUpsert) UpdateUpdatedAt() *SpaceQuotaUpsert {
	u.SetExcluded(spacequota.FieldUpdatedAt)
	return u
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *SpaceQuotaUpsert) AddUpdatedAt(v int64) *SpaceQuotaUpsert {
	u.Add(spacequota.FieldUpdatedAt, v)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *SpaceQuotaUpsert) ClearUpdatedAt() *SpaceQuotaUpsert {
	u.SetNull(spacequota.FieldUpdatedAt)
	return u
}

// SetQuotaType sets the "quota_type" field.
func (u *SpaceQuotaUpsert) SetQuotaType(v string) *SpaceQuotaUpsert {
	u.Set(spacequota.FieldQuotaType, v)
	return u
}

// UpdateQuotaType sets the "quota_type" field to the value that was provided on create.
func (u *SpaceQuotaUpsert) UpdateQuotaType() *SpaceQuotaUpsert {
	u.SetExcluded(spacequota.FieldQuotaType)
	return u
}

// SetQuotaName sets the "quota_name" field.
func (u *SpaceQuotaUpsert) SetQuotaName(v string) *SpaceQuotaUpsert {
	u.Set(spacequota.FieldQuotaName, v)
	return u
}

// UpdateQuotaName sets the "quota_name" field to the value that was provided on create.
func (u *SpaceQuotaUpsert) UpdateQuotaName() *SpaceQuotaUpsert {
	u.SetExcluded(spacequota.FieldQuotaName)
	return u
}

// SetMaxValue sets the "max_value" field.
func (u *SpaceQuotaUpsert) SetMaxValue(v int64) *SpaceQuotaUpsert {
	u.Set(spacequota.FieldMaxValue, v)
	return u
}

// UpdateMaxValue sets the "max_value" field to the value that was provided on create.
func (u *SpaceQuotaUpsert) UpdateMaxValue() *SpaceQuotaUpsert {
	u.SetExcluded(spacequota.FieldMaxValue)
	return u
}

// AddMaxValue adds v to the "max_value" field.
func (u *SpaceQuotaUpsert) AddMaxValue(v int64) *SpaceQuotaUpsert {
	u.Add(spacequota.FieldMaxValue, v)
	return u
}

// SetCurrentUsed sets the "current_used" field.
func (u *SpaceQuotaUpsert) SetCurrentUsed(v int64) *SpaceQuotaUpsert {
	u.Set(spacequota.FieldCurrentUsed, v)
	return u
}

// UpdateCurrentUsed sets the "current_used" field to the value that was provided on create.
func (u *SpaceQuotaUpsert) UpdateCurrentUsed() *SpaceQuotaUpsert {
	u.SetExcluded(spacequota.FieldCurrentUsed)
	return u
}

// AddCurrentUsed adds v to the "current_used" field.
func (u *SpaceQuotaUpsert) AddCurrentUsed(v int64) *SpaceQuotaUpsert {
	u.Add(spacequota.FieldCurrentUsed, v)
	return u
}

// SetUnit sets the "unit" field.
func (u *SpaceQuotaUpsert) SetUnit(v string) *SpaceQuotaUpsert {
	u.Set(spacequota.FieldUnit, v)
	return u
}

// UpdateUnit sets the "unit" field to the value that was provided on create.
func (u *SpaceQuotaUpsert) UpdateUnit() *SpaceQuotaUpsert {
	u.SetExcluded(spacequota.FieldUnit)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *SpaceQuotaUpsert) SetEnabled(v bool) *SpaceQuotaUpsert {
	u.Set(spacequota.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *SpaceQuotaUpsert) UpdateEnabled() *SpaceQuotaUpsert {
	u.SetExcluded(spacequota.FieldEnabled)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.SpaceQuota.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(spacequota.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SpaceQuotaUpsertOne) UpdateNewValues() *SpaceQuotaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(spacequota.FieldID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(spacequota.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SpaceQuota.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SpaceQuotaUpsertOne) Ignore() *SpaceQuotaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SpaceQuotaUpsertOne) DoNothing() *SpaceQuotaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SpaceQuotaCreate.OnConflict
// documentation for more info.
func (u *SpaceQuotaUpsertOne) Update(set func(*SpaceQuotaUpsert)) *SpaceQuotaUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SpaceQuotaUpsert{UpdateSet: update})
	}))
	return u
}

// SetSpaceID sets the "space_id" field.
func (u *SpaceQuotaUpsertOne) SetSpaceID(v string) *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetSpaceID(v)
	})
}

// UpdateSpaceID sets the "space_id" field to the value that was provided on create.
func (u *SpaceQuotaUpsertOne) UpdateSpaceID() *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateSpaceID()
	})
}

// ClearSpaceID clears the value of the "space_id" field.
func (u *SpaceQuotaUpsertOne) ClearSpaceID() *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.ClearSpaceID()
	})
}

// SetDescription sets the "description" field.
func (u *SpaceQuotaUpsertOne) SetDescription(v string) *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SpaceQuotaUpsertOne) UpdateDescription() *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SpaceQuotaUpsertOne) ClearDescription() *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.ClearDescription()
	})
}

// SetExtras sets the "extras" field.
func (u *SpaceQuotaUpsertOne) SetExtras(v map[string]interface{}) *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetExtras(v)
	})
}

// UpdateExtras sets the "extras" field to the value that was provided on create.
func (u *SpaceQuotaUpsertOne) UpdateExtras() *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateExtras()
	})
}

// ClearExtras clears the value of the "extras" field.
func (u *SpaceQuotaUpsertOne) ClearExtras() *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.ClearExtras()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *SpaceQuotaUpsertOne) SetCreatedBy(v string) *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SpaceQuotaUpsertOne) UpdateCreatedBy() *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *SpaceQuotaUpsertOne) ClearCreatedBy() *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *SpaceQuotaUpsertOne) SetUpdatedBy(v string) *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *SpaceQuotaUpsertOne) UpdateUpdatedBy() *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *SpaceQuotaUpsertOne) ClearUpdatedBy() *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SpaceQuotaUpsertOne) SetUpdatedAt(v int64) *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *SpaceQuotaUpsertOne) AddUpdatedAt(v int64) *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SpaceQuotaUpsertOne) UpdateUpdatedAt() *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *SpaceQuotaUpsertOne) ClearUpdatedAt() *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetQuotaType sets the "quota_type" field.
func (u *SpaceQuotaUpsertOne) SetQuotaType(v string) *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetQuotaType(v)
	})
}

// UpdateQuotaType sets the "quota_type" field to the value that was provided on create.
func (u *SpaceQuotaUpsertOne) UpdateQuotaType() *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateQuotaType()
	})
}

// SetQuotaName sets the "quota_name" field.
func (u *SpaceQuotaUpsertOne) SetQuotaName(v string) *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetQuotaName(v)
	})
}

// UpdateQuotaName sets the "quota_name" field to the value that was provided on create.
func (u *SpaceQuotaUpsertOne) UpdateQuotaName() *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateQuotaName()
	})
}

// SetMaxValue sets the "max_value" field.
func (u *SpaceQuotaUpsertOne) SetMaxValue(v int64) *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetMaxValue(v)
	})
}

// AddMaxValue adds v to the "max_value" field.
func (u *SpaceQuotaUpsertOne) AddMaxValue(v int64) *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.AddMaxValue(v)
	})
}

// UpdateMaxValue sets the "max_value" field to the value that was provided on create.
func (u *SpaceQuotaUpsertOne) UpdateMaxValue() *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateMaxValue()
	})
}

// SetCurrentUsed sets the "current_used" field.
func (u *SpaceQuotaUpsertOne) SetCurrentUsed(v int64) *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetCurrentUsed(v)
	})
}

// AddCurrentUsed adds v to the "current_used" field.
func (u *SpaceQuotaUpsertOne) AddCurrentUsed(v int64) *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.AddCurrentUsed(v)
	})
}

// UpdateCurrentUsed sets the "current_used" field to the value that was provided on create.
func (u *SpaceQuotaUpsertOne) UpdateCurrentUsed() *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateCurrentUsed()
	})
}

// SetUnit sets the "unit" field.
func (u *SpaceQuotaUpsertOne) SetUnit(v string) *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetUnit(v)
	})
}

// UpdateUnit sets the "unit" field to the value that was provided on create.
func (u *SpaceQuotaUpsertOne) UpdateUnit() *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateUnit()
	})
}

// SetEnabled sets the "enabled" field.
func (u *SpaceQuotaUpsertOne) SetEnabled(v bool) *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *SpaceQuotaUpsertOne) UpdateEnabled() *SpaceQuotaUpsertOne {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *SpaceQuotaUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SpaceQuotaCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SpaceQuotaUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SpaceQuotaUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: SpaceQuotaUpsertOne.ID is not supported by MySQL driver. Use SpaceQuotaUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SpaceQuotaUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SpaceQuotaCreateBulk is the builder for creating many SpaceQuota entities in bulk.
type SpaceQuotaCreateBulk struct {
	config
	err      error
	builders []*SpaceQuotaCreate
	conflict []sql.ConflictOption
}

// Save creates the SpaceQuota entities in the database.
func (_c *SpaceQuotaCreateBulk) Save(ctx context.Context) ([]*SpaceQuota, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SpaceQuota, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SpaceQuotaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SpaceQuotaCreateBulk) SaveX(ctx context.Context) []*SpaceQuota {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SpaceQuotaCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SpaceQuotaCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SpaceQuota.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SpaceQuotaUpsert) {
//			SetSpaceID(v+v).
//		}).
//		Exec(ctx)
func (_c *SpaceQuotaCreateBulk) OnConflict(opts ...sql.ConflictOption) *SpaceQuotaUpsertBulk {
	_c.conflict = opts
	return &SpaceQuotaUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SpaceQuota.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SpaceQuotaCreateBulk) OnConflictColumns(columns ...string) *SpaceQuotaUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SpaceQuotaUpsertBulk{
		create: _c,
	}
}

// SpaceQuotaUpsertBulk is the builder for "upsert"-ing
// a bulk of SpaceQuota nodes.
type SpaceQuotaUpsertBulk struct {
	create *SpaceQuotaCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SpaceQuota.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(spacequota.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *SpaceQuotaUpsertBulk) UpdateNewValues() *SpaceQuotaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(spacequota.FieldID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(spacequota.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SpaceQuota.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SpaceQuotaUpsertBulk) Ignore() *SpaceQuotaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SpaceQuotaUpsertBulk) DoNothing() *SpaceQuotaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SpaceQuotaCreateBulk.OnConflict
// documentation for more info.
func (u *SpaceQuotaUpsertBulk) Update(set func(*SpaceQuotaUpsert)) *SpaceQuotaUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SpaceQuotaUpsert{UpdateSet: update})
	}))
	return u
}

// SetSpaceID sets the "space_id" field.
func (u *SpaceQuotaUpsertBulk) SetSpaceID(v string) *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetSpaceID(v)
	})
}

// UpdateSpaceID sets the "space_id" field to the value that was provided on create.
func (u *SpaceQuotaUpsertBulk) UpdateSpaceID() *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateSpaceID()
	})
}

// ClearSpaceID clears the value of the "space_id" field.
func (u *SpaceQuotaUpsertBulk) ClearSpaceID() *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.ClearSpaceID()
	})
}

// SetDescription sets the "description" field.
func (u *SpaceQuotaUpsertBulk) SetDescription(v string) *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetDescription(v)
	})
}

// UpdateDescription sets the "description" field to the value that was provided on create.
func (u *SpaceQuotaUpsertBulk) UpdateDescription() *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateDescription()
	})
}

// ClearDescription clears the value of the "description" field.
func (u *SpaceQuotaUpsertBulk) ClearDescription() *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.ClearDescription()
	})
}

// SetExtras sets the "extras" field.
func (u *SpaceQuotaUpsertBulk) SetExtras(v map[string]interface{}) *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetExtras(v)
	})
}

// UpdateExtras sets the "extras" field to the value that was provided on create.
func (u *SpaceQuotaUpsertBulk) UpdateExtras() *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateExtras()
	})
}

// ClearExtras clears the value of the "extras" field.
func (u *SpaceQuotaUpsertBulk) ClearExtras() *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.ClearExtras()
	})
}

// SetCreatedBy sets the "created_by" field.
func (u *SpaceQuotaUpsertBulk) SetCreatedBy(v string) *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetCreatedBy(v)
	})
}

// UpdateCreatedBy sets the "created_by" field to the value that was provided on create.
func (u *SpaceQuotaUpsertBulk) UpdateCreatedBy() *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateCreatedBy()
	})
}

// ClearCreatedBy clears the value of the "created_by" field.
func (u *SpaceQuotaUpsertBulk) ClearCreatedBy() *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.ClearCreatedBy()
	})
}

// SetUpdatedBy sets the "updated_by" field.
func (u *SpaceQuotaUpsertBulk) SetUpdatedBy(v string) *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetUpdatedBy(v)
	})
}

// UpdateUpdatedBy sets the "updated_by" field to the value that was provided on create.
func (u *SpaceQuotaUpsertBulk) UpdateUpdatedBy() *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateUpdatedBy()
	})
}

// ClearUpdatedBy clears the value of the "updated_by" field.
func (u *SpaceQuotaUpsertBulk) ClearUpdatedBy() *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.ClearUpdatedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SpaceQuotaUpsertBulk) SetUpdatedAt(v int64) *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetUpdatedAt(v)
	})
}

// AddUpdatedAt adds v to the "updated_at" field.
func (u *SpaceQuotaUpsertBulk) AddUpdatedAt(v int64) *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.AddUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SpaceQuotaUpsertBulk) UpdateUpdatedAt() *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *SpaceQuotaUpsertBulk) ClearUpdatedAt() *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.ClearUpdatedAt()
	})
}

// SetQuotaType sets the "quota_type" field.
func (u *SpaceQuotaUpsertBulk) SetQuotaType(v string) *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetQuotaType(v)
	})
}

// UpdateQuotaType sets the "quota_type" field to the value that was provided on create.
func (u *SpaceQuotaUpsertBulk) UpdateQuotaType() *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateQuotaType()
	})
}

// SetQuotaName sets the "quota_name" field.
func (u *SpaceQuotaUpsertBulk) SetQuotaName(v string) *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetQuotaName(v)
	})
}

// UpdateQuotaName sets the "quota_name" field to the value that was provided on create.
func (u *SpaceQuotaUpsertBulk) UpdateQuotaName() *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateQuotaName()
	})
}

// SetMaxValue sets the "max_value" field.
func (u *SpaceQuotaUpsertBulk) SetMaxValue(v int64) *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetMaxValue(v)
	})
}

// AddMaxValue adds v to the "max_value" field.
func (u *SpaceQuotaUpsertBulk) AddMaxValue(v int64) *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.AddMaxValue(v)
	})
}

// UpdateMaxValue sets the "max_value" field to the value that was provided on create.
func (u *SpaceQuotaUpsertBulk) UpdateMaxValue() *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateMaxValue()
	})
}

// SetCurrentUsed sets the "current_used" field.
func (u *SpaceQuotaUpsertBulk) SetCurrentUsed(v int64) *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetCurrentUsed(v)
	})
}

// AddCurrentUsed adds v to the "current_used" field.
func (u *SpaceQuotaUpsertBulk) AddCurrentUsed(v int64) *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.AddCurrentUsed(v)
	})
}

// UpdateCurrentUsed sets the "current_used" field to the value that was provided on create.
func (u *SpaceQuotaUpsertBulk) UpdateCurrentUsed() *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateCurrentUsed()
	})
}

// SetUnit sets the "unit" field.
func (u *SpaceQuotaUpsertBulk) SetUnit(v string) *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetUnit(v)
	})
}

// UpdateUnit sets the "unit" field to the value that was provided on create.
func (u *SpaceQuotaUpsertBulk) UpdateUnit() *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateUnit()
	})
}

// SetEnabled sets the "enabled" field.
func (u *SpaceQuotaUpsertBulk) SetEnabled(v bool) *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *SpaceQuotaUpsertBulk) UpdateEnabled() *SpaceQuotaUpsertBulk {
	return u.Update(func(s *SpaceQuotaUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *SpaceQuotaUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SpaceQuotaCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SpaceQuotaCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SpaceQuotaUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
