// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"ncobase/tenant/data/ent/tenantgroup"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// TenantGroup is the model entity for the TenantGroup schema.
type TenantGroup struct {
	config `json:"-"`
	// ID of the ent.
	// primary key
	ID string `json:"id,omitempty"`
	// tenant id
	TenantID string `json:"tenant_id,omitempty"`
	// group id
	GroupID string `json:"group_id,omitempty"`
	// id of the creator
	CreatedBy string `json:"created_by,omitempty"`
	// id of the last updater
	UpdatedBy string `json:"updated_by,omitempty"`
	// created at
	CreatedAt int64 `json:"created_at,omitempty"`
	// updated at
	UpdatedAt int64 `json:"updated_at,omitempty"`
	// Type of relationship between tenant and group
	RelationType string `json:"relation_type,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TenantGroup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tenantgroup.FieldCreatedAt, tenantgroup.FieldUpdatedAt:
			values[i] = new(sql.NullInt64)
		case tenantgroup.FieldID, tenantgroup.FieldTenantID, tenantgroup.FieldGroupID, tenantgroup.FieldCreatedBy, tenantgroup.FieldUpdatedBy, tenantgroup.FieldRelationType:
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TenantGroup fields.
func (tg *TenantGroup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tenantgroup.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				tg.ID = value.String
			}
		case tenantgroup.FieldTenantID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tenant_id", values[i])
			} else if value.Valid {
				tg.TenantID = value.String
			}
		case tenantgroup.FieldGroupID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				tg.GroupID = value.String
			}
		case tenantgroup.FieldCreatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field created_by", values[i])
			} else if value.Valid {
				tg.CreatedBy = value.String
			}
		case tenantgroup.FieldUpdatedBy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field updated_by", values[i])
			} else if value.Valid {
				tg.UpdatedBy = value.String
			}
		case tenantgroup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				tg.CreatedAt = value.Int64
			}
		case tenantgroup.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				tg.UpdatedAt = value.Int64
			}
		case tenantgroup.FieldRelationType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field relation_type", values[i])
			} else if value.Valid {
				tg.RelationType = value.String
			}
		default:
			tg.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TenantGroup.
// This includes values selected through modifiers, order, etc.
func (tg *TenantGroup) Value(name string) (ent.Value, error) {
	return tg.selectValues.Get(name)
}

// Update returns a builder for updating this TenantGroup.
// Note that you need to call TenantGroup.Unwrap() before calling this method if this TenantGroup
// was returned from a transaction, and the transaction was committed or rolled back.
func (tg *TenantGroup) Update() *TenantGroupUpdateOne {
	return NewTenantGroupClient(tg.config).UpdateOne(tg)
}

// Unwrap unwraps the TenantGroup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (tg *TenantGroup) Unwrap() *TenantGroup {
	_tx, ok := tg.config.driver.(*txDriver)
	if !ok {
		panic("ent: TenantGroup is not a transactional entity")
	}
	tg.config.driver = _tx.drv
	return tg
}

// String implements the fmt.Stringer.
func (tg *TenantGroup) String() string {
	var builder strings.Builder
	builder.WriteString("TenantGroup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", tg.ID))
	builder.WriteString("tenant_id=")
	builder.WriteString(tg.TenantID)
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(tg.GroupID)
	builder.WriteString(", ")
	builder.WriteString("created_by=")
	builder.WriteString(tg.CreatedBy)
	builder.WriteString(", ")
	builder.WriteString("updated_by=")
	builder.WriteString(tg.UpdatedBy)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", tg.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", tg.UpdatedAt))
	builder.WriteString(", ")
	builder.WriteString("relation_type=")
	builder.WriteString(tg.RelationType)
	builder.WriteByte(')')
	return builder.String()
}

// TenantGroups is a parsable slice of TenantGroup.
type TenantGroups []*TenantGroup
